### ISSUE TITLE
The --primaryDarkBG and --secondaryDarkBG are not rendering as the correct colors

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#100]
## Problem/Concern
The colors for the --primaryDarkBG and --secondaryDarkBGshould be darker versions of the primary-900 color and they just look grey

* [link to problem content]()

**Comment by aaronreed708** [comment]
This is a very old issue.  @lwnoble can you verify that this is still a problem?

**Comment by evangk6** [comment]
Duplicate of #656
