### ISSUE TITLE
I only have 1 color and primary color but when I click on a dropdown in the theme area I have 3 rows of colors

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#102]
## Problem/Concern
<img width="469" alt="Screenshot 2023-04-11 at 1 41 53 PM" src="https://user-images.githubusercontent.com/6164440/231246044-b8c51bd2-568a-4590-9efc-7f86590230fb.png">
* [link to problem content]()

## Proposed Solution
There should only be one row if I only have a primary color
There should only be two rows if I have a primary and a secondary color and they are different
There should only be three rows if primary, secondly and tertiary are different colors

**Comment by brycecurtis** [comment]
Dup of #167.
