### ISSUE TITLE
Elevation backgrounds are not being passed into the css

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#105]
--elevation-bg-0
--elevation-bg-1
--elevation-bg-2
--elevation-bg-3
--elevation-bg-4
--elevation-bg-5
--elevation-bg-6
--elevation-bg-7
--elevation-bg-8
--elevation-bg-9

* [link to problem content]()

## Proposed Solution
The colors should be the selected dark mode back ground with white overlayed on top in increasing brightness.

**Comment by brycecurtis** [comment]
This has been resolved.
