### ISSUE TITLE
State Colors not rendering

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#106]
The states all appear white with black text in light mode  and all balck with white text in dark mode in the Theme Builder UI
<img width="597" alt="Screenshot 2023-04-11 at 1 01 04 PM" src="https://user-images.githubusercontent.com/6164440/231254560-04a253c4-663b-4e8b-b9cd-1e6bb86f9dbf.png">
roblem content]()
* [link to p

**Comment by aaronreed708** [comment]
I believe that this was fixed by https://github.com/discoverfinancial/a11y-theme-builder-sdk/commit/c7ef62577a604b7abfce522023612cc6e4314d4f in the sdk.  Please pull latest and verify whether this issue still exists for you or not.

**Comment by brycecurtis** [comment]
This has been resolved.
