### ISSUE TITLE
Dropdown menu should be left aligned not center aligned

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#107]
The dropdown menus look odd center aligned.

* [link to p
<img width="611" alt="Screenshot 2023-04-11 at 1 59 07 PM" src="https://user-images.githubusercontent.com/6164440/231255332-2585e066-1010-49b7-a0e9-fc2322737ed8.png">
roblem content]()

They should left align with the button.

**Comment by brycecurtis** [comment]
This is a dup of #178.  However, the dropdown is still center aligned.
