### ISSUE TITLE
Wrong and missing atributes

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#115]
Things that are wrong:
--backgroundSecondary
--on-backgroundSecondary
—onbuttonOnBlack
—buttonOnTertiary
—onButtonOnTertiary
—gradient-3
—on-gradient-3
--buttonOnGradient1
—onbuttonOnGradient1
--buttonOnGradient2
—onbuttonOnGradient2
--buttonOnGradient3
—onbuttonOnGradient3
--dm-on-background-tertiary

Missing:
--dmhotlinkOnWhite:’’;
--dmhotlinkDecorationOnWhite: '';
--dmhotlinkOnBlack:'';
--dmhotlinkDecorationOnBlack: '';

* [link to problem content]()

**Comment by brycecurtis** [comment]
This has been resolved.  However, the var names have been changed to be consistent.

--dm-hotlinkOnWhite
--dm-hotlinkOnWhite-decoration
--dm-hotlinkOnBlack
--dm-hotlinkOnBlack-decoration
