### ISSUE TITLE
[Admin] Getting organized!

### ISSUE THREAD

**Issue by vinomaster** [finos/a11y-theme-builder#126]
## Problem/Concern
Need to discuss how the project will be organized including logistics for meetings, triage, milestone definitions and collaborating.

See example missing details [here](https://github.com/discoverfinancial/a11y-theme-builder/blob/main/CONTRIBUTE.md)

## Proposed Solution

We should consider the use of GitHub Wiki, Projects, and Discussions. 

Some well organized projects, like [Backstage]( https://backstage.io), include topics such as:

- [Community Sessions (Replays)](https://backstage.io/on-demand/)
- [Community Sessions](https://github.com/backstage/community) Notes/Schedules (See Calendar)
- [Office Hours](https://info.backstage.spotify.com/office-hours)

**Comment by vinomaster** [comment]
A suggestion from @andybs  was that we may want to host maybe a M/W or T/Th office hours for both DT & Hack the code, maybe one early on day 1 and a later meeting on day 2 to address timezones.

Also this issue is related to #14

**Comment by brycecurtis** [comment]
This has been resolved and is similar to #14, which is resolved.
