### ISSUE TITLE
[TB] Darkmode dropdown colors

### ISSUE THREAD

**Issue by brycecurtis** [finos/a11y-theme-builder#129]
## Problem/Concern

Darkmode dropdown, hover color, border hard to see if theme palette is red

**Comment by brycecurtis** [comment]
Aaron to verify

**Comment by aaronreed708** [comment]
Here is what I'm seeing in the dropdown atom, comparing light and dark modes.

In light mode, notice that the outline of the combobox, the currently selected item (option 1) and the item being hovered (option 3) are all easily identifiable:



![Image](https://user-images.githubusercontent.com/32913837/231839826-f777432d-28e7-4ab0-9ba7-2bb97a93ad27.png)

**Comment by aaronreed708** [comment]
In dark mode, it is very difficult to see the outline of the combobox and the currently selected item.  The item being hovered is also hard to differentiate from the other items:



![Image](https://user-images.githubusercontent.com/32913837/231840742-423870f4-c5de-4511-86f7-efbc407dc18d.png)

**Comment by brycecurtis** [comment]
A solution has been found that uses the Select.MenuProps.container property with a reference div.  A new Dropdown component will be created in the mui-a11y-tb/components directory.
