### ISSUE TITLE
[TB] Review Contribution Guide for both project repos

### ISSUE THREAD

**Issue by vinomaster** [finos/a11y-theme-builder#14]
## Problem/Concern
Review content of [CONTRIBUTE.md](https://github.com/discoverfinancial/a11y-theme-builder/blob/main/CONTRIBUTE.md)
Review inline comments for missing data.

* [link to problem content]()

## Proposed Solution
Update any/all missing data / comtent.

**Comment by brycecurtis** [comment]
Need to identify communication channels.

**Comment by brycecurtis** [comment]
This is complete.
