### ISSUE TITLE
[TB] For the Hero Organism - change the radio color selector to a drop down

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#148]
## Problem/Concern
For the Hero - there will be miltiple options for the user to select from:
Default
Black
White
Gradient-1
Gradient-2
Gradient-3

* [link to problem content]()

## Proposed Solution
So rather than having 6 radio buttons we should put the selectables in a drop down menu

**Comment by brycecurtis** [comment]
This has been resolved.
