### ISSUE TITLE
[TB] Organisms should have a light dark mode toggle

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#151]
## Problem/Concern
Currently you can only see the hero in light mode

* [link to problem content]()

## Proposed Solution
We should add the same light/dark mode toggle that is available for components

**Comment by brycecurtis** [comment]
The solution was to add Hero to components.
If organisms have light and dark mode switch, then should molecules and atoms?  This needs discussion.

**Comment by aaronreed708** [comment]
Because we already have this functionality working in another spot in the code, implementing this functionality for Organisms should be straight forward.  A possible good "first bug" for a contributor.

**Comment by evangk6** [comment]
waiting for verification by @lwnoble

**Comment by aaronreed708** [comment]
Closing this as complete.  If improvements need to be made, they can be done on a different issue.
