### ISSUE TITLE
[TB] Dropdown molecule example not reflecting the changes being made in the settings

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#165]
## Problem/Concern

If I set the border radius for the dropdown molecule to be 0px, I would expect the dropdown to be rectangular with 90 degree corners.  If I change the selection to be full item instead of "left border only", I would expect the dropdown to show selected menu items where the item background color changes when selected or hovered, but I am not seeing that.

**Comment by brycecurtis** [comment]
Border radius is being removed.

**Comment by evangk6** [comment]
Given Bryce's comment above, and my screenshot of no border radius setting present:
![image](https://user-images.githubusercontent.com/36457549/233169907-3d4995f9-e113-48da-b5b5-b2f0fca60559.png)

This issue is complete.
