### ISSUE TITLE
[TB] Button color

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#167]
## Problem/Concern

If a user creates a new design system and only selects one color in the Color Palette atom and then proceeds through the Color Themes atom initializing the default theme for the design system, they will be presented with 3 identical rows of shades in the dropdowns used to select button color, icon color and gradient text colors.

<img width="730" alt="Screenshot 2023-04-13 at 1 52 11 PM" src="https://user-images.githubusercontent.com/32913837/231844560-c0c6308b-7d4c-4d92-acae-c540cba395f1.png">

**Comment by brycecurtis** [comment]
Three rows should only be rendered when primary, secondary & teriary color names are different.

**Comment by aaronreed708** [comment]
Discussed at scrum today with Bryce, Evan, Keith and myself.  @smithbk was worried about the case where the user may start initializing the default color theme, get down past the button color and then go back and change the secondary or tertiary color away from all using the same color to use different colors.

We should discuss again when @lwnoble is available and make sure that we are all on the same page as to the user experience that we want the user to have.

**Comment by brycecurtis** [comment]
Resolution is to not show duplicate rows.  If primary, secondary or tertiary shades are changed, then invalidate and clear these settings.

**Comment by brycecurtis** [comment]
SDK update complete. UI needs to clear settings upon receiving notification of property with undefined value from sdk.

**Comment by aaronreed708** [comment]
I added code to the color components used in CreateColorTheme to handle ValueChanged events.  This can happen if user works their way down the Color Theme page specifying values to fields  but then changing a color like "primary" in the color theme which all of the fields depend on.  The design system in the sdk will then unset (setting them to undefined) all of those property values.
