### ISSUE TITLE
[TB] No feedback to user when user saves design system

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#168]
## Problem/Concern

If a user updates a design system and clicks on the "Save" button next to the "Current design system" dropdown on the design system top action bar, the user gets no feedback as to whether the save completed and was successful or not

## Proposed Solution

The user should get some kind of visual indication that the save was completed and was successful or if an error occurred.  Maybe a spinner shows with button disabling (and then a checkmark showing with a re-enabled button when complete) on the button, or some status message ('save pending', then 'save completed') appears under the button.

**Comment by brycecurtis** [comment]
@lwnoble will investigate UI design - possibly using toast message to display as a general solution that can be used for other notifications.

**Comment by lwnoble** [comment]
![Group 1](https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/4d0e5387-70b5-4379-842f-a0b2888136ba)

The toast should animate in from the right, pause and then animate quickly off the screen to the right.

**Comment by evangk6** [comment]
`ds.store()` is a promise void, but it will throw an error if it doesn't save. So the last thing I need to do here is catch any error from this function.

**Comment by evangk6** [comment]
Merged in main
