### ISSUE TITLE
[SDK] Dark mode text gradient is wrong

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#210]
## Problem/Concern
The dark mode text gradient is the same as the light mode text but it should be different

* [link to problem content]()

**Comment by brycecurtis** [comment]
Based upon the CSS being set, the values are different.  Closing issue.

--gradient1-a	#E4CACA	
--on-gradient1-a	#121212	
--dm-gradient1-a	#D3AAAA	
--dm-on-gradient1-a	#121212	

--gradient1-b	#B97878	
--on-gradient1-b	#121212	
--dm-gradient1-b	#B26969	
--dm-on-gradient1-b	#121212	

--gradient2-a	#E4CACA	
--on-gradient2-a	#121212	
--dm-gradient2-a	#D3AAAA	
--dm-on-gradient2-a	#121212

--gradient2-b	#C79393	
--on-gradient2-b	#121212	
--dm-gradient2-b	#BC7E7E	
--dm-on-gradient2-b	#121212
