### ISSUE TITLE
[SDK] Border opacity needs to change from .15 to .25

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#212]
## Problem/Concern
Currently the light mode border is --border: rgba(0,0,0,0.15);
the dark mode border is --dm-border: rgba(255,255,255,0.15);

* [link to problem content]()

## Proposed Solution
please change them to:
light mode = border: --rgba(0,0,0,0.25);
the dark mode border is --dm-border: rgba(255,255,255,0.25);

**Comment by smithbk** [comment]
done
