### ISSUE TITLE
[TB] Input Background Colors are not updating upon selection

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#237]
## Problem/Concern

* [link to problem content]()

**Comment by brycecurtis** [comment]
Waiting for clarification from @lwnoble

**Comment by aaronreed708** [comment]
@lwnoble said today that the problem is that the textfield's background color isn't changing in the following scenario:

1. load the the pre-defined Sample design system
2. navigate to the Atoms->Input Background page
3. change the "overlay color" from the default "white" to another selection from the "Overlay Color" dropdown

Lise expects that the input background in both the light mode section and the dark mode section should change which does seem to be happening in the light mode section but not the dark mode section.

**Comment by aaronreed708** [comment]
I'm assigning to @smithbk as the UI is clearly changing the property value that is bound to that select component.  It also looks like the sdk is doing something as I see the opacity for the CSS variable, `--dm-input`, changing by 0.06.  But the RGB value is NOT changing.  I also see the same behavior using the **My Design** pre-defined design system.

**Comment by smithbk** [comment]
@lwnoble Lise, I'm blocked and need help.  I'm including both mine and your code below.  The order of the if's in my code is the same as in yours.

When I tested with CP_BLACK_OFFBLACK selected for my dark mode background and when I switch between "White Background" and "Primary Background" for the input overlay selection, I see the value of --dm-input changing from rgba(143,81,81,0.54) (for White Background) to rgba(143,81,81,0.6) (for Primary Background).  Obviously the difference isn't discernable.

My code ...
```
        let dmInputDefault: Shade;
        if (dmbg.title === ColorTheme.CP_BLACK_OFFBLACK) {
            if (inputOverlayIsWhite) {
                dmInputDefault  = this.avgShade([dmbgPrimary, 'rgba('+primaryDark+',.08)']);
            } else {
                dmInputDefault  = this.avgShade([dmbgPrimary, 'rgba('+primaryDark+',.2)']);
            }
        } else if (dmbg.title === ColorTheme.CP_800_900) {
            if (inputOverlayIsWhite) {
                dmInputDefault = this.avgShade([pHex, 'rgba('+overlayRGB+',.2)']);
            } else {
                dmInputDefault = this.avgShade([pHex, 'rgba('+overlayRGB+',.2)']);
            }
        } else {
            throw new Error(`Invalid title for dark mode background: ${dmbg.title}`)
        }
```

And here is your code ... with the if's and else's in the same order between yours and mine

```
if (dmbackgroundPrimaryName.replace(/\s/g, '') == 'nearblack-bg') {
   if (inputOverlay == '#FFFFFF') {
    dminputDefault  = chroma.average([dmbackground, 'rgba('+primaryDark+',.08)']).css();
    dminputDisabled = chroma.average([dmbackground, 'rgba(0,0,0,.3)']).css();
   } else {
    dminputDefault  = chroma.average([dmbackground, 'rgba('+primaryDark+',.2)']).css()
    dminputDisabled = chroma.average([dmbackground, 'rgba(0,0,0,.3)']).css();
   }
  } else {
   if (inputOverlay == '#FFFFFF') {
    dminputDefault  = chroma.average([dmbackground, 'rgba('+overlayRGBArray+',.2)']).css();
    dminputDisabled = chroma.average([dmbackground, 'rgba(0,0,0,.3)']).css();
   } else {
    dminputDefault  = chroma.average([dmbackground, 'rgba('+overlayRGBArray+',.2)']).css();
    dminputDisabled = chroma.average([dmbackground, 'rgba(0,0,0,.3)']).css();
   }
  }
```

**Comment by lwnoble** [comment]
The color does not change from colored to white.  When I select the white from the drop down the dark mode is input is still:
--dm-input: rgba(131,86,86,0.54);

The above should  be:

        let dmInputDefault: Shade;
        if (dmbg.title === ColorTheme.CP_BLACK_OFFBLACK) {
            if (inputOverlayIsWhite) {
                dmInputDefault  = this.avgShade([dmbgPrimary, 'rgba(255,255,255,.08)']);
            } else {
                dmInputDefault  = this.avgShade([dmbgPrimary, 'rgba('+primaryDark+',.2)']);
            }
        } else if (dmbg.title === ColorTheme.CP_800_900) {
            if (inputOverlayIsWhite) {
                dmInputDefault = this.avgShade([pHex, 'rgba('+overlayRGB+',.2)']);
            } else {
                dmInputDefault = this.avgShade([pHex, 'rgba('+overlayRGB+',.2)']);
            }
        } else {
            throw new Error(`Invalid title for dark mode background: ${dmbg.title}`)
        }

But, I am not sure why the for the dm input is coming in a lot darker:
--dm-input: rgba(131,86,86,0.6);

It has an opacity of .6 not .2 as outlined above
