### ISSUE TITLE
[SDK] If you add a color after you start building a theme the new color added is not added as an option in the drop down menus

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#240]
## Problem/Concern

* [link to problem content]()

**Comment by aaronreed708** [comment]
The Primary, Secondary and Tertiary ColorSelect's are bound to their respective PropertyColorShade's from the ColorTheme class in the sdk.  The shades that appear in their dropdown trays are populated by calling PropertyColorShade.getSelectableValues().  ColorSelect also registers a listener on the property to listen for notifications should the selectable list change.  The sdk isn't notifying the color select which makes me think that the sdk is not handling the additional colors correctly.

**Comment by smithbk** [comment]
@aaronreed708 fixed ... please verify

**Comment by aaronreed708** [comment]
@smithbk fix verified, closing issue
