### ISSUE TITLE
[TB] Slider Bar inset bevel is not working

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#243]
## Problem/Concern

Sliders Molecule Inverse Bevel is not working:
![image](https://user-images.githubusercontent.com/36457549/233170694-4001f1cb-0d7e-455b-8908-ba77bcc66c6d.png)

**Comment by evangk6** [comment]
I am unclear what "Bar Inset Shadow" refers to.
If it is inverse elevation, these do not exist.
If it is inverse bevel, these can not exist at the same time that elevation does.

The original ThemeBuilder does not have a working example so it is not clear how this should look.
I can see that the `boxShadow` is being set to `sliderhandleElevation`, which is being correctly set to the elevation I select. Any value for Bar Inset Shadow would have to change this variable, which would make this an SDK issue.

I will need some clarification on this, before proceeding.

**Comment by evangk6** [comment]
"Bar Inset Shadow" = Inverse Bevel
It's fine to keep the naming the way it is here.

The `Elevation` setting applies to the slider handle and is working.
**The `Bar Inset Shadow` setting should apply to the slider bar itself.**

I can confirm that the `Bar Inset Shadow` setting dropdown changes the SDK's `slidersMolecule.barInsetShadow` property.
Lise/Keith to fix the CSS, or myself when I return.

**Comment by brycecurtis** [comment]
@evangk6 will investigate.

**Comment by lwnoble** [comment]
All items with elevations or shadows will now have one drop down with all
the various shadow effects to pick from:

None
Elevations 1-9
Bevels 1-9
Inset Bevel 1-9
Ridge 1-9
Groove 1-8
Glow 1-9

They can only pick one.

This is the same for the bar, handle, buttons, cards, etc.

**Comment by brycecurtis** [comment]
This may be resolved with new shadow effect.  Revisit when that's done.

**Comment by aaronreed708** [comment]
Issue Bryce is referring to here is #413

**Comment by aaronreed708** [comment]
Discussed in meeting today.  @lwnoble we have some questions.  Using the Sliders Molecule as the basis of the questions:

- On Slider's page, Handle Elevation and Bar Inset Shadow should become one consolidated dropdown?
  - if so, which current functionality should be removed?  The ability to affect the slider handle or the ability to affect the slider bar?
- The single dropdown should have all 50+ shadow-ish options even though currently only elevation and inverse bevel shadow options are used?

**Comment by lwnoble** [comment]
So both the handle and the bar should have a dropdown .

Each dropdown should have the 50+ shadow options.

We will want to replace the 50+ shadow dropdown anywhere in the app where users assign elevations or bevels.

**Comment by lwnoble** [comment]
![Group 1](https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/7fc1a97d-807e-4641-9b36-f13773d426ec)

**Comment by lwnoble** [comment]
![Group 1](https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/a5c0cae8-cfb8-4b83-b02f-91194cad4683)

**Comment by aaronreed708** [comment]
> So both the handle and the bar should have a dropdown .
> 
> Each dropdown should have the 50+ shadow options.
> 
> We will want to replace the 50+ shadow dropdown anywhere in the app where users assign elevations or bevels.

So this is a 1:1 replacement, correct?  If a molecule has two or more different dropdowns based on elevations, bevels, etc (like slider does), then each field would remain, with each having the 50+ dropdown?

**Comment by aaronreed708** [comment]
@lwnoble verified that this is a 1:1 substitution.  So any kind of elevation, bevel or glow dropdown should present the user with the 50+ dropdown.

**Comment by aaronreed708** [comment]
Aaron to verify

**Comment by aaronreed708** [comment]
In the latest code, it looks like selecting these values in the slider atom panel in the Handle Shadow or Bar Shadow dropdowns results in a var(--sliderbar-shadow) or var(--sliderhandle-shadow) that is undefined:

- Inset Bevel
- Recess

Reassigning to @smithbk

**Comment by aaronreed708** [comment]
@aaronreed708 to reverify still occurs

**Comment by aaronreed708** [comment]
@smithbk this issue still occurs.  I confirmed with Inset Bevel 9 and Recess 9 values for slider bar shadow

**Comment by smithbk** [comment]
Fixed ... please verify

**Comment by aaronreed708** [comment]
I verified that the sliderbar-shadow and sliderhandle-shadow now have values when I build theme builder with sdk v0.0.22.  Closing.
