### ISSUE TITLE
[DOCS] Add targetted browsers

### ISSUE THREAD

**Issue by brycecurtis** [finos/a11y-theme-builder#260]
## Problem/Concern

Add targetted browsers for ThemeBuilder in dev guide doc & mkdoc under prereq/depenencies

**Comment by aaronreed708** [comment]
I came up with:

- Chrome v109+
- Safari v15.6+
- Edge v110+
- Firefox v111+

I used the following criteria to reach this list:

_We should support any browser that at least 10% of their users are using_

To build the list I used data from https://gs.statcounter.com/browser-version-market-share/desktop/worldwide/#monthly-202204-202304.  Too hard to get good information from the line graph here, though.  Click on "Download Data (.csv)" will give all of the information as a .csv file for a lot of browser versions.

**Comment by aaronreed708** [comment]
As a reference, the browsers targeted by Discover.com are listed here: https://www.discover.com/credit-cards/browser-support/ and at this time consist of:

* Firefox 65.0 and higher 
* Chrome 68.0 and higher 
* Safari 12.0 and higher 
* Edge 79.0 and higher
