### ISSUE TITLE
[TB] We should have fonts in a dropdown list (the list of top 100 google fonts) and then only allow user to select the available font weights

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#264]
## Problem/Concern

* [link to problem content]()

**Comment by evangk6** [comment]
This is completed except for the font weight portion.

@lwnoble - when you get a moment could you please remind me which of font weights 0-4 use the primary or secondary fonts?

**Comment by evangk6** [comment]
@lwnoble - this is merged into main and ready for review.

Things to look at:
- Whether the functionality you are looking for is working
- Whether the UI looks reasonable
- Whether the UX makes sense e.g. the warnings and weight restrictions

If there are any issues or improvements please record them here, and I will fix. Thanks!

**Comment by aaronreed708** [comment]
Fixed in latest code per @lwnoble
