### ISSUE TITLE
[TB] Cannot cancel modal dialog on samples page

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#304]
## Problem/Concern

1. Go to the page that lists the sample design systems.
2. Click on the Sample design system
3. Click on the 3 dots
4. Click on View Design System Data

A modal dialog showing the design system data is shown.  Clicking on "Cancel" button doesn't do anything.

## Proposed Solution

Clicking on "Cancel" should dismiss the modal dialog.

**Comment by brycecurtis** [comment]
Fixed with commit https://github.com/discoverfinancial/a11y-theme-builder/commit/1d166367f5fe7e7ca02ad9437cb7c3310a391c8b
