### ISSUE TITLE
[TB] Sample and Design System Cards show pointer cursor but not actionable 

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#323]
## Problem/Concern

When the user hovers their cursor/mouse over one of our design system cards in either the "Your Design Systems" or "Sample and Template Design Systems" sections, it turns into a pointer (finger pointing icon) that is usually reserved for things that are actionable like a hotlink, checkbox or a button.  While these design system cards used to be actionable (double clicking would load them), they are no longer.

## Proposed Solution

To follow Mui behavior, a card itself shouldn't get the pointer cursor when hovered, only actionable items on the card should get a pointer cursor when hovered.

**Comment by brycecurtis** [comment]
Decided that double-click was not expected behavior based upon other cards in the TB app.  The design system name on the card is single-clickable and the mouse pointer changes to indicate such.
