### ISSUE TITLE
[TB] Decide if CTA LARGE in button molecule should capitalize all letters

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#326]
## Problem/Concern

I noticed that selecting CTA LARGE option in UI used to ensure that all buttons have capitalized text, but that no longer seems to be the case.  Looking at: https://ux.stackexchange.com/questions/125378/does-it-matter-if-i-capitalise-my-call-to-action, there isn't a consensus whether Call To Action buttons SHOULD have capitalized text.  I think that we need to make the decision, capture here in this issue, and then make sure that the CTA options have the appropriate capitalization.

## Proposed Solution

I would think that if the option reads "CTA LARGE", then the text should be capitalized in addition to having larger font size.  If it should just be a larger font size, then it should probably read "CTA Large".

**Comment by brycecurtis** [comment]
This should be changed to uppercase.
