### ISSUE TITLE
[TB] Decide on button elevation and bevel behavior

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#327]
## Problem/Concern

I noticed that my button molecules don't show bevel if elevation is 1, but will for any other value of elevation (including elevation-0).  Is that correct behavior?  If elevation-1 should NOT show bevel but elevation-0 SHOULD, then wouldn't it be an inverse bevel?  If so, that isn't what I'm seeing.

In Lise's prototype, both No Elevation and Elevation-1 seem to block bevel from being applied to a button.  Which, as mentioned above, is not what Theme Builder shows.

**Comment by aaronreed708** [comment]
According to the documentation at: http://127.0.0.1:8000/a11y-theme-builder/architecture/base-services/#elevations,

"_Use the background color which serves as the elevation 0 shade and apply an increasing white overlay on the colors to generate 10 shades_".

So that sounds to me like elevation-0 should show no shadowing, but all of the other elevations should show increasing shadow length (or lightness, depending on light mode vs dark mode) .

**Comment by brycecurtis** [comment]
This is addressed with styling issues (#412).
