### ISSUE TITLE
[TB] Support padding, fix Hero organism

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#341]
## Problem/Concern

Per @lwnoble, there should be a padding property on the Hero organism.  @smithbk is adding this property to the organism.hero class in the sdk.  Keith also fixed some other CSS variables.

- should gap for the whole hero?
- should padding be only vertical (top and bottom)?  And for which sections?  Breadcrumbs, title and body?

## Proposed Solution

This issue is meant to get Hero working correctly:

- [ ] get breadcrumbs (e.g. underlining hotlinks with dark backgrounds) working correctly will all background selections
- [ ] make sure hotlinks component is using the correct CSS variables for black and white backgrounds
- [x] get padding working correctly
- [x] get gaps working correctly
- [x] get padding and gap dropdowns to show calculated value, not multiplier value

**Comment by aaronreed708** [comment]
@lwnoble verified that I should only be applying padding to the top and bottom of the hero and allowing gap to determine the vertical spacing inside the hero. I will make that update

**Comment by brycecurtis** [comment]
Issue #357 created to track remaining breadcrumb issue.  Closing.
