### ISSUE TITLE
[TB] No gradient header text in darkmode

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#342]
## Problem/Concern

The gradient header text in darkmode on the Color Themes atom (after the default color theme has been set) isn't legible.  Are we using the wrong CSS variable here?

## Proposed Solution

The gradient header text should be visible and easily readable.

**Comment by aaronreed708** [comment]
Here is a design system that shows the issue in Atoms->Color Theme

[foobar-design-system.txt](https://github.com/discoverfinancial/a11y-theme-builder/files/11376438/foobar-design-system.txt)

To use:

1. Copy the contents of the file above to the clipboard
2. Click the "Import a Design System" button on the Your Designs page
3. Enter a name for the new design system
4. Paste clipboard into the "Design System data" field
5. Click the "Next" button

Then click the "Load Design System" option off of the new design system's card.

**Comment by aaronreed708** [comment]
Here's what it looks like:

<img width="1095" alt="Screenshot 2023-05-02 at 2 32 19 PM" src="https://user-images.githubusercontent.com/32913837/235754506-7a18869b-055e-4a79-9d04-6a6f3caf5432.png">

**Comment by aaronreed708** [comment]
It kinda looks like the problem is because if the To or From color that is calculated in the dark mode gradient header text is just too close in color to the dark mode background.  But it does appear that there is calculation there.  The light mode gradient and the dark mode gradient for the header text  is definitely different.  The CSS var that is affected is: --dm-text-gradient.  In the failing case above, the gradient in light and dark mode seem identical.  But if I load the "My Design" design system, there does appear to be a difference, though subtle, between light and dark mode.

**Comment by smithbk** [comment]
done
