### ISSUE TITLE
[TB] Create Hero example under Components

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#356]
## Problem/Concern

For consistency sake, we need to create an example of Hero under components where it can easily be placed into darkmode so that users can visualize its appearance in the most likely scenarios, just like with molecules.  Perhaps, when we do that, we separate the radio buttons showing variants from the settings  so that only the settings appears in the organisms tab for Hero and only the radio buttons changing variant values is under the components tab for Hero.

## Proposed Solution

This is my proposal:

- [ ] We create a Hero nav item in the left nav bar under Components.  I think that this makes sense because we have the Hero component under code/src/mui-a11y-tb/components
- [ ] We have our current Hero example with the variant radio buttons on the Hero component page
- [ ] We remove the variant radio buttons from the Hero under the Organisms tab

**Comment by aaronreed708** [comment]
Need to still make this work well in darkmode and get @lwnoble to sign off on darkmode behavior.

**Comment by lwnoble** [comment]
I have fixed the on button and button color for darkmode gradient 1,2, and 3 but the dm-gradient-3-a and dm-gradient-3-b are getting update by the sdk incorrectly.  Infact the sdk does not need to pass along these values at all as the are static.

They are set in the TB.css file as:

--dm-gradient3-a: var(--dm-gray-700);
--dm-gradient3-b: var(--black);

and they are getting over written to:

--dm-gradient3-a: var(--dm-gray-0);
--dm-on-gradient3-b: var(--dm-white);

**Comment by brycecurtis** [comment]
These static css variables will be updated in sdk.

**Comment by smithbk** [comment]
This has been fixed in version 0.0.13 of the SDK
