### ISSUE TITLE
[TB] Fix hotlink underlining for breadcrumbs

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#357]
## Problem/Concern

On the most recent level of code (v0.0.6 of SDK), hotlink CSS variable values are now being generated correctly for breadcrumbs, giving the appropriate contrast in darkmode.  However, I've noticed that the text decoration is not being picked up correctly by the UI due to conflicting style rules.

Steps to recreate:
- Load pre-defined "Samples" design system
- Navigate to Organisms->Hero
- Select "Black" variant.  Notice that the breadcrumb links are NOT underlined, that is a problem because the hotlink setting in the "Sample" design system is that underlining of hotlinks is on by default.
- Hover over one of the hotlinks in the breadcrumbs.

Notice that the hotlinks do NOT become underlined.  According to @lwnoble there needs to be a visual differentiation between hotlinks being hovered or focused and the default hotlink state.  For Theme Builder, this differentiation should be underlining previously not-underlined hotlinks or removing the underline for a hotlink that, by default, is underlined.

These issues appear to be due to be conflicting style rules that are preventing the hero hotlink text-decoration CSS variable from being applied to the breadcrumbs in Hero.

## Proposed Solution

Ensure Atoms->Hotlinks, Organisms->Hero and Components->Colors->Hotlinks and Components->Breadcrumbs are all working correctly.

**Comment by brycecurtis** [comment]
This has been resolved except for issue opened in #366.
