### ISSUE TITLE
[DOCS] Create videos

### ISSUE THREAD

**Issue by brycecurtis** [finos/a11y-theme-builder#36]
## Problem/Concern

The ThemeBuilder's vision and usage need to be conveyed to the users of the tool.

## Proposed Solution

Create one or more videos:
1. ThemeBuilder application intro and how it can be run (Lise)
2. How designers can use ThemeBuilder (Evan)
3. How developers can use ThemeBuilder (Evan)

**Comment by brycecurtis** [comment]
Integrate videos for Github Pages

**Comment by vinomaster** [comment]
@evangk6 Once you create the sample video place it into the `docs/_videos` folder and then it can be linked to using the docs pages.

**Comment by brycecurtis** [comment]
Designer video is similar to developer video, so will add additional clips & publish as new video.  (Evan)
