### ISSUE TITLE
[TB] New design system remembers previous visits

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#361]
## Problem/Concern

If I've worked with a couple of different design systems like Sample and My Design and then create a new design system, it begins the experience at the last place I was with a previous design system rather than at the introduction for Atoms.

## Proposed Solution

Create a new design system should always start the user at the beginning, especially since it is very likely that their previous visits were to pieces of the UI that will not be unavailable due to the design system not having a default color palette.

**Comment by brycecurtis** [comment]
The solution was to create a Preferences component that is used to store to LocalStorage for each design system.  When a design system is deleted, it's preference values are deleted from LocalStorage too.
