### ISSUE TITLE
[TB] Issues with Hotlinks color swatches

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#366]
## Problem/Concern

Steps to recreate:
1. Load "My Design" pre-defined design system
2. Go to Atoms->Hotlinks, select "No" for default underlining in light mode
3. Click on Components tab
4. Select Dark Mode
5. Click on Components->Colors->Hotlinks

You'll notice that in the Dark Hotlinks section that all three text samples are underlined, but not all samples under White Hotlinks are which seems inconsistent.  It also appears that the white styles in this section aren't synchronized with the black styles in this section (e.g. white text is underlined with hardcoding, black text is using var(-hotlinkOnBlack-decoration)).

Assigning to @lwnoble.  If Lise can give me the proper behavior, I'm happy to fix it.

For example, should black and white have pre-set rules here or are they adapting to design system atom and molecule settings?

**Comment by brycecurtis** [comment]
Cannot be reproduced.  @aaronreed708 to verify if this is still a problem.

**Comment by aaronreed708** [comment]
@brycecurtis @lwnoble We missed step #2 in the instructions when trying to recreate today.  You have to set default underlining to "no", then try to load the Components->Colors->Hotlinks **in darkmode**.  You'll see this, which I believe is incorrect:

<img width="1073" alt="Screenshot 2023-06-07 at 2 58 35 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/32913837/f96796ff-90a4-470f-9fa9-828a52fc323c">
