### ISSUE TITLE
[DOCS] Internationalization of Impaired Persons

### ISSUE THREAD

**Issue by vinomaster** [finos/a11y-theme-builder#368]
## Problem/Concern

The GAAD Hackathon raised the concern that the term **Impaired Person** is not favorable in Ireland/UK region.

## Proposed Solution
Identify alternative vernacular and update all documentation and/or repo references.
![image](https://user-images.githubusercontent.com/505186/236864330-558eea6b-18dc-4ea4-a4a7-057398ed8f30.png)

**Comment by evangk6** [comment]
how about? “**person with disability**” / people needing accommodations

We could reply to the person and see if they have a preference?

**Comment by aaronreed708** [comment]
I believe that "people needing accommodations" might be better since "person with disability" to me seems to fit what the originator said about "saying someone had a disorder" having negative connotations in the UK, Ireland.

**Comment by kris-reed** [comment]
@aaronreed708 "People needing accommodations" is an excellent suggestion.

**Comment by aaronreed708** [comment]
@Kayd396 thank you for agreeing to take a stab at updating the documentation!  Ping me on Slack if you need help with any of it and we can get on a call and discuss.

**Comment by kris-reed** [comment]
@aaronreed708 Sounds like a plan! Thank you for considering me. I should have time to look it over this weekend (4/27-28).

**Comment by aaronreed708** [comment]
@Kayd396 can this issue be closed?

**Comment by aaronreed708** [comment]
Kris verified this is fixed.  Closing.

**Comment by aaronreed708** [comment]
Hi @kris-reed, can you please read my Slack message to you?  We need you to please set the email property in your GitHub settings so that the EasyCLA stuff will work correctly.  Right now the fix that you did for this issue is causing problems when I try to move it to main.  Thanks!
