### ISSUE TITLE
[REQUEST] Add support for WCAG 2.2

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#380]
## Suggestion/Concern

It looks like the [WCAG 2.2](https://www.w3.org/TR/WCAG22/) publication date is imminent as the projected publication date has already passed.  We need to put this on our radar and in our plans.  Accessibility.com has [an article](https://www.accessibility.com/blog/what-to-expect-in-the-new-wcag-2.2) highlighting what is new in WCAG 2.2.

## Proposed Solution

Update Theme Builder to be WCAG 2.2 compliant.

**Comment by brycecurtis** [comment]
@lwnoble investigated and determined that there are no changes to be implemented for WCAG 2.2.
