### ISSUE TITLE
[TB] Review bevel behavior

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#381]
## Problem/Concern

I see in the Atoms->Bevel page what I believe is an inconsistency.  It seems weird to me that with the regular bevels we apply the lighting and shading affect to a greater degree for each level yet the position of the light source doesn't change.  It just appears to change strength.  If I extend that behavior to inverse bevel, then, as the name inverse bevels implies, I'd expect the same thing with just the lighting source moved diagonally across the element (so moved from upper left corner to bottom right corner).  Yet the CSS vars for inverse bevels have no lighting effect and the shadow seems to move from left to right as the level increases (implying that the light source is moving) but doesn't get any deeper (so light source isn't changing strength)

## Proposed Solution

We need to document the proper behavior and capture it somewhere.  And, of course, implement it if it needs to be different.

**Comment by brycecurtis** [comment]
@lwnoble Please review that rendering is correct.

**Comment by aaronreed708** [comment]
I found this: https://cssdeck.com/blog/options-to-set-css-bevel-border/
<img width="769" alt="Screenshot 2023-05-12 at 5 02 42 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/32913837/4e3f96b5-58ef-4269-b966-63b49a52a57b">

I would think that the outset example is bevel and the inset example is the inverse bevel.

**Comment by lwnoble** [comment]
The above examples are  borders.  But I have updated the inset bevels.  

We could add new styling to create the groove and ridge looks with box shadows.  I will be looking into this.

**Comment by brycecurtis** [comment]
This is being addressed by shadows (#412)
