### ISSUE TITLE
[TB] Should we expose reverse elevation in UI?

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#382]
## Problem/Concern

While documenting CSS vars I noticed that there is a set of CSS vars like --reverse-elevation-horizontal and --reverse-elevation-vertical.  Which just seem to be the negative values of --elevation-horizontal and --elevation-vertical.  I would think that we'd want to display samples showing what the --reverse-elevation-* effects would be on an element (instead of above ground elevation it would be below-ground depth, I assume).  Should we have a switch that toggles the view (currently light and dark mode examples) between hill and hole?

We also need confirmation that the affects for a hole are just the inverse of the hill and that there should not be a separate set of controls for holes.  Currently if I change --elevation-horizontal then --reverse-elevation-horizontal changes, too.  If this is the desired behavior we need to make sure that this is captured in the documentation.

**Comment by aaronreed708** [comment]
As follow up, it looks like reverse-elevation-veritcal and reverse-elevation-horizontal exist, but they are not currently being used.  There is currently no --reverse-elevation-1, for example.  So these would also need to be in place before we can demonstrate these in the UI.

**Comment by brycecurtis** [comment]
@lwnoble Is an example of this needed?

**Comment by brycecurtis** [comment]
Per @lwnoble, these can be removed.  Closing.
