### ISSUE TITLE
[TB] UI issues with small window sizes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#383]
## Problem/Concern

If I size the Theme Builder application to fit in a smaller space (like 50% the size of the screen) I run into issues with some of the pages.  For example on the Font Settings page.

<img width="986" alt="Screenshot 2023-05-11 at 1 58 40 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/32913837/4ddfcf2c-55e8-47d6-abe5-7d1e4b311c2e">

Notice that you can't see what the primary font is used for.

This will become much more important if we want to support Theme Builder on mobile devices, like tablets.

**Comment by brycecurtis** [comment]
Destktop is the current device targetted.  If app is hosted, then a tablet might be used.  Move this to future consideration.

**Comment by lwnoble** [comment]
I have added grid systems to make the pages responsive
