### ISSUE TITLE
[TB] Dark mode Gradient3 color in components isn't visible

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#395]
## Problem/Concern

Steps to recreate:

1. Load "Sample" design system
2. Select Components tab
3. Turn on dark mode
4. Select Components->Colors->Gradients

I don't see anything for Gradient 3.  It looks like --dm-gradient-3 and --dm-on-gradient-3 values are incorrect.  I'm seeing `--dm-on-gradient-3: #121212` and  `--dm-gradient-3: linear-gradient(45deg, var(--dm-gradient3-a) 0%, var(--dm-gradient3-b) 100%);`. Where `--dm-gradient-3a: #121212` and `--dm-gradient-3b: #121212`

Components->Hero->Gradient 3 also seems to be broken.  I assume that it is related.

**Comment by lwnoble** [comment]
Fixed and pushed code.
