### ISSUE TITLE
[TB] Dark mode menu icons not showing

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#396]
## Problem/Concern

Steps to recreate:

1. Load "Sample" design system
2. Select Components tab
3. Select Components->Menus->Menu with Icons button

You should see a menu dropdown with icons to the left of each item's text.  Currently there is just blank space.  Seems to be a CSS conflict issue.

**Comment by brycecurtis** [comment]
This occurs in dark mode.



![Image](https://github.com/discoverfinancial/a11y-theme-builder/assets/329897/09bf77f7-27a9-4e3c-a5bd-0007a85d8461)

**Comment by lwnoble** [comment]
Fixed and pushed code
