### ISSUE TITLE
[TB] Design System cards don't handle long titles well

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#399]
## Problem/Concern

When I put in a long name for a design system, the text extends past the end of the card.

<img width="889" alt="Screenshot 2023-06-01 at 12 32 49 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/32913837/3d578de3-55cc-4a36-9935-dec912efb42b">

## Proposed Solution

The card title should wrap or have ellipsis that can be hovered to see full text

**Comment by brycecurtis** [comment]
This happens if the name is all one word, otherwise it does wrap at spaces.

**Comment by brycecurtis** [comment]
This has been fixed.
