### ISSUE TITLE
[TB] Docker instructions incorrect for volume

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#401]
## Problem/Concern

I used the instructions in https://github.com/discoverfinancial/a11y-theme-builder/blob/main/DEV_GUIDE.md#start-new-container, on my Macbook ,where it says to run the image using:

```
docker run -p 8080:3001 -v ${pwd}:/code/src/data --name a11y-theme-builder -d a11y-theme-builder
```

But when I do that and then create a design system and save it, I would expect the design system to survive stopping and restarting the container since it is setting up a volume in the current directory.  However, this isn't the case.  If I run:

```
docker stop a11y-theme-builder && docker rm a11y-theme-builder
```

and then re-run the `docker run` command above, the design system is no longer there.

## Proposed Solution

It looks like the issue is the ${pwd} above.  This has no meaning on macos.  So it is essentially setting the volume to "".

**Comment by aaronreed708** [comment]
So if I change to use `$(pwd)`, then the volume works, but the volume contains a `theme` file with 0 bytes.  So essentially the DB is empty, with no samples or pre-loaded design systems.  This is because when binding a volume to a host directory, the volume is initialized with the contents of the host directory, which in my case had no existing `theme` file.

So we can change to use a named Docker volume (e.g. created with `docker volume create`) which will then be initialized with the container's directory contents.  OR we could do something like specifying the theme builder data directory using an environment variable, binding the volume to that specified directory and then using an ENTRYPOINT script (which runs in the container) to copy the default `theme` file into that directory if the environment variable and the directory itself exists but the directory is empty.

It seems to me that the named Docker volume is the cleanest way to go.  But it also means it will take some Docker knowledge for a developer to go see what is actually in the file (either finding the directory on the host machine that the named volume is using or using `docker exec` to look into the running container).

**Comment by smithbk** [comment]
Just change `pwd` to `PWD` and it should work

```docker run -p 8080:3001 -v ${PWD}:/code/src/data --name a11y-theme-builder -d a11y-theme-builder```

**Comment by aaronreed708** [comment]
Added instructions to developer's guide to create a named docker volume and added that to run instructions for the docker image.  Added instructions and warning for deleting the volume.
