### ISSUE TITLE
[TB] Dynamically load Google Fonts

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#405]
## Problem/Concern

Regardless if the user enters the font name in an input field or from a dropdown the interface will not update to the user's selected font unless they happen to have the font on their local system and the resulting react component library will only render the selected font for end users who also happen to have the font on their local system.

* [link to problem content]()

## Proposed Solution
To Solve this we need to be able to
1.) dynamically update either a link to the font in the header to the index file or 
2.) dynamically import the font in the css file.
3.) use java script to dynamically load the font

Examples of the two options:

1.) Update the links in the header
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,100;1,200&display=swap" rel="stylesheet">

2.)  Import the font in the css
@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;1,100;1,200&display=swap');

3.) I found the following code pen about dynamically loading google fonts:
https://codepen.io/trent48/pen/RQzBvo

Once we have this functionality the ux will update upon input from the end user and we can not only allow them to select fonts from a give dropdown but we can allow the to select "Other" and type in a Google Font name.  In this case however they will need to manually enter font weight as google does not specify the available font weights for each font.

**Comment by lwnoble** [comment]
Here is a sample UX with dropdown menu selectors that load the fonts dynamically

[LoadFont.zip](https://github.com/discoverfinancial/a11y-theme-builder/files/11667877/LoadFont.zip)

**Comment by evangk6** [comment]
Fonts are loaded when input as of https://github.com/discoverfinancial/a11y-theme-builder/pull/433, so I am closing this one.
Any tweaks or UI changes will be done before https://github.com/discoverfinancial/a11y-theme-builder/issues/264 is closed.
