### ISSUE TITLE
[TB] Change Elevation and Bevel Dropdown selectors to Shadows

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#414]
## Problem/Concern

Now that we have multiple shadow styles we should offer the styles in one Shadow dropdown menu

* [link to problem content]()

## Proposed Solution

Shadow:
<Select>
None
**Elevations**
Elevation 1

Elevation 2
Elevation 3
Elevation 4
Elevation 5
Elevation 6
Elevation 7
Elevation 8
Elevation 9
**Bevels*
Bevel 1
Bevel 2
Bevel 3
Bevel 4
Bevel 5
Bevel 6
Bevel 7
Bevel 8
Bevel 9
**Inset Bevels**
Inset Bevel 1
Inset Bevel 2
Inset Bevel 3
Inset Bevel 4
Inset Bevel 5
Inset Bevel 6
Inset Bevel 7
Inset Bevel 8
Inset Bevel 9
**Grooves**
Groove 1
Groove 2
Groove 3
Groove 4
Groove 5
Groove 6
Groove 7
Groove 8
Groove 9
**Ridges**
Ridge 1
Ridge 2
Ridge 3
Ridge 4
Ridge 5
Ridge 6
Ridge 7
Ridge 8
Ridge 9
**Recessed**
Recess 1
Recess 2
Recess 3
Recess 4
Recess 5
Recess 6
Recess 7
Recess 8
Recess 9

**Comment by brycecurtis** [comment]
Dup of #413
