### ISSUE TITLE
[TB][SDK] Add new shadow group and glow atom

### ISSUE THREAD

**Issue by brycecurtis** [finos/a11y-theme-builder#422]
## Problem/Concern

Create a "Shadow" group.  Atoms under this group are "Elevation", "Bevels", "Glows".

## Proposed Solution

Properties needed for GlowAtom:
```
{
    glow-rgb: #, #, #;  //color picker, default=rgb from --primary-color
    glow-blur: pixels (0-100); //slider, default=2px
    glow-spread: pixels (0-100); //slider, default=2px
    glow-opacity: number (0-100) divided by 100 ; //slider, default=.2
    glow-change: number (0-100) divided by 100 ; //slider, default=.2
}
```

**Comment by brycecurtis** [comment]
@lwnoble will create css for these new variables.

**Comment by lwnoble** [comment]
The CSS Code will just pass along the variables.

The JSON Code should output the following:

"Glow-Info": {
  "Change": {
    "type": "other",
    "value": "0.2"
  },
  "Spread": {
    "type": "other",
    "value": "2px"
  },
  "Blur": {
    "type": "other",
    "value": "2px"
  },
  "Opacity": {
    "type": "other",
    "value": "0.04"
  },
  "RGB": {
    "type": "other",
    "value": "0, 0, 0"
  },
},

**Comment by lwnoble** [comment]
I have added the following to the TB.css file

  --glow-blur: 2px;
  --glow-spread: 2px;
  --glow-rgb: 0, 0, 0;
  --glow-opacity: 0.2;
  --glow-change: 0.2;

**Comment by smithbk** [comment]
@brycecurtis @aaronreed708 The SDK portion of this has been completed

**Comment by aaronreed708** [comment]
I'm not exactly sure what UI to build for this issue.  Am I correct in assuming that this new Shadows group is to go in the Components tab?  Like the Colors and Typography groups?  And just show swatches?

Or is the goal of this issue to add a group to the Atoms tab, like the Typography group, and move the Elevation and Bevel atoms under there?  What would the Glow look like, then?  Just move the two "glow" bevels out of Bevels into a new atom?

**Comment by aaronreed708** [comment]
Discussed in today's call.  Keith added an atom for Glow so I need to:

- Create group called Shadow under Atoms
- Move Bevels and Elevations atoms to the new group
- Create a new atom panel for Glows

So the remaining questions are:

1. What should be in the Glow atom panel?
   1. should it be a color picker component and 4 sliders affecting 4 bevels representing blur, spread, opacity and change?  
1. Do I move/remove the "Light Glow Opacity" and "Dark Glow Opacity" bevels out of the Bevels atom panel?
   1. Or should Light and dark glow opacities in bevels make use of the new CSS glow variables?
