### ISSUE TITLE
[TB] Add a Templates section along the top nav

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#431]
## Problem/Concern

I would like to start pulling components together into templates.

So we need to add a tab and a left nav with light mode/dark mode for templates.

* [link to problem content]()

## Proposed Solution

As is:
<img width="1133" alt="Screenshot 2023-07-21 at 9 53 47 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/7c35739b-f0af-4b0e-a49a-20d76b1955c9">

To Be:
<img width="1135" alt="Screenshot 2023-07-21 at 9 54 40 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/909cc1d3-06bf-45ad-b17b-d8e41aa16b56">

**Comment by brycecurtis** [comment]
@lwnoble is investigating.

**Comment by aaronreed708** [comment]
Per @lwnoble this is complete.  Closing.
