### ISSUE TITLE
[SDK] New Issue Title

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#442]
## Problem/Concern

I have a core JSON file loaded in Figma Tokens and was then exporting light mode and dark mode JSON.

I now believe we need to couple all the JSON in my core with the light mode.  Dark mode can stay the same.

* [link to problem content]()

## Proposed Solution

Here is the totality of the Core JSON:
[core.txt](https://github.com/discoverfinancial/a11y-theme-builder/files/12220403/core.txt)

**Comment by aaronreed708** [comment]
@lwnoble is this still an issue?  Can you please give it a title if it is?

**Comment by aaronreed708** [comment]
@lwnoble believes that this has been fixed.  Closing.
