### ISSUE TITLE
[SDK] Input bg color for black incorrect

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#447]
## Problem/Concern
Currently, if the background is black the input bg (--input)  is rgba(254,252,254,0.55);

<img width="242" alt="Screenshot 2023-08-02 at 10 41 11 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/d2d3aa58-8261-4c29-ac2b-b4726cf4831c">

* [link to problem content]()

## Proposed Solution
If the light mode background is black the input bg (--input) should be  rgba(254,252,254,0.05);
<img width="239" alt="Screenshot 2023-08-02 at 10 44 17 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/2b17062e-eb70-4b23-8672-de81fceff680">

**Comment by aaronreed708** [comment]
@lwnoble can you please verify that you want this change ONLY if this is an input on a black light-mode background?  And ONLY inside TB and not necessarily generated in the JSON/CSS?  So I assume that the change would live in this section of the code under `[data-background="black"]` -> https://github.com/finos/a11y-theme-builder/blob/f14faa67144cb9fd4854b70e6791b1629feb9787/code/src/ui/src/mui-a11y-tb/themes/TB.css#L2649.  Is that correct?  Or does this change need to affect input backgrounds in applications that are using Theme Builder-built design systems and thus belong in the SDK?  I'm guessing the former.

**Comment by aaronreed708** [comment]
@ravjot07 Worked with @lwnoble, we were unable to recreate this issue on inputs with data-background="black".  Not sure where the screenshot came from.  Closing.
