### ISSUE TITLE
[TB] Setup FINOS Landscape Location

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#484]
## Problem/Concern

We need to decide where TB would go in the FINOS Landscape. Suggestions were `UI Frameworks` or `Innovation`.
This issue should remain open until TB is present on the Landscape.

**Comment by aaronreed708** [comment]
Discussed with FINOS and we believe that this should be under Innovation.  Follow up with Mao

**Comment by evangk6** [comment]
I have clarified this information with Maurizio and Juan. As mentioned, this issue will remain open until TB is visible.

**Comment by evangk6** [comment]
I heard back from Maurizio who said the following:

> normally the landscape category is something that FINOS chooses, based of course on the feedback gathered from the contributors.

> The "Enablement > Innovation" category was created specifically for Zenith, our Emerging Technologies SIG, which is currently the only entry in that category; having the theme builder there would not be a good fit in my opinion. Arguably, the name of this category is too generic, and a lot of projects may want to belong here, which would eventually defeat the purpose of a categorized landscape.

> Also the "Enablement > ODP Toolchain" (ODP stands for Open Developer Platform, which is the collection of collaborative tools that FINOS have designed to enable oss collaboration for our hosted projects) could be a good fit, given that the Theme Builder can be considered a tool to improve accessibility of your web applications.

> The "Applications > UI Frameworks" fits perfectly in my opinion, and it's populated with frontend applications/libraries that are much more similar to the theme builder.

> I'd suggest starting by adding the Theme Builder into either the "Applications > UI Frameworks" or "Enablement > ODP Toolchain" , depending whether you want to emphasize more the "enablement" aspect of the project, rather than its nature as a frontend application; let me know what you think.

To summarize, he is saying that FINOS will choose the category. "Innovation" may not be the right choice here, because it is too generic.

`Enablement > ODP Toochain` could be a good fit. `Applications > UI Frameworks` could be a perfect fit. Either is a good way to start depending on whether we want to focus more on the "enablement" aspect or the frontend application itself.

**Comment by aaronreed708** [comment]
This was discussed in call on Tuesday, it is going to live under Applications -> UI Frameworks. Closing.
