### ISSUE TITLE
[TB] Align Repo to FINOS Blueprint

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#485]
## Problem/Concern

We need to approve the suggested changes in https://github.com/discoverfinancial/a11y-theme-builder/pull/478.
We may not be able to do this until the code is transferred.

**Comment by aaronreed708** [comment]
reviewed, looks good.  Will be merged after transfer.  Closing

**Comment by aaronreed708** [comment]
Merged today.  Closing.
