### ISSUE TITLE
[SDK] Tertiary Color Hotlink Color Wrong

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#500]
## Problem/Concern
<img width="663" alt="Screenshot 2023-09-06 at 10 13 49 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/270b5c9f-cccf-4df9-8a4d-ca9fb1684f4e">

The Hotlink Color for the Teritart Color should be white or black, not colored.

Currently the --hotlinkOnTertiary is coming through as purple in this example

* [link to problem content]()

**Comment by smithbk** [comment]
Fix checked in and waiting for @lwnoble to verify before closing
