### ISSUE TITLE
[TB] Quiet Text Color Opacity

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#502]
## Problem/Concern

For all the text there is normal text and quiet text.

Quiet text is used for less critical text but it still needs to have a contrast of 3.1:1.

Can we calculate a quiet opacity level for text on the following:

Primary
Secondary
Tertiary
Black
White

* [link to problem content]()

Currently, they all have an opacity of .75 - so are all by default the contrast ratio of the normal text and the background * .75.

In Dark mode, if the text is white you would get the opacity by getting the contrast ratio of (#ffffff and the background * .6.) and then multiply that by .75 .

If it does not meet the contrast ration we will adjust the .75 to the appropriate amount to get 3.1:1 or higher.

**Comment by aaronreed708** [comment]
This issue is being addressed by #803 so closing per @lwnoble.
