### ISSUE TITLE
[REQUEST] Implement Color Cards organism

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#503]
## Suggestion/Concern

It might be useful to implement a Color Card organism like the "Cards, White" organism that ensures that any text or SVG images on the card use an appropriately contrasting color to maintain accessibility standards.

For information on how to extend our atomic components, please read: https://a11y-theme-builder.finos.org/developers/add-atomic-elements/#extending-the-user-interface

**Comment by alexvera1** [comment]
Taking a look at this for GHC

**Comment by aaronreed708** [comment]
@alexvera1 Please contact me should you need any help/guidance on this issue.  Thank you!

**Comment by aaronreed708** [comment]
Hi @alexvera1, I just wanted to reach out one more time to see if you need any help making progress on your contribution.  You can respond to me here or you can reach out to me directly on Slack.  More information on communicating with the Theme Builder community can be found here: https://github.com/finos/a11y-theme-builder/wiki/Communication#communication-channels.  I hope to hear from you soon!

**Comment by aaronreed708** [comment]
No feedback from contributor, returning to the pool

**Comment by msdorothyewuah** [comment]
@aaronreed708 the link in the issue description returns a 404

**Comment by aaronreed708** [comment]
Our documentation moved when the repo moved under FINOS.  Here is the new link: https://a11y-theme-builder.finos.org/developers/add-atomic-elements/#extending-the-user-interface

**Comment by evangk6** [comment]
This feature is not needed anymore as we move toward a different approach.
