### ISSUE TITLE
[REQUEST] Implement an image list molecule

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#518]
## Suggestion/Concern

This issue is to build a MUI Image List-based molecule that could then be built into organisms or templates.  Such a component would have to observe all of the accessibility rules as they relate to text and background contrasts, etc.

For information on how to extend our atomic components, please read: https://a11y-theme-builder.finos.org/developers/add-atomic-elements/#extending-the-user-interface

**Comment by omesh-omg** [comment]
hello @aaronreed708 can you assign this issue to me I want to get familiar with theme-builder SDK

**Comment by omesh-omg** [comment]
I have some question regarding this @aaronreed708 

- how will this show up in the left navigation bar 
- what different type of image lists do I have to show
- We have to use the latest version of MUI probably yes
- We should make all different types of image list  variants available to user to select from {quilted, standard, masonry, woven}
- And also the  design has to comeup with previous preferences of user right
- Also for this to implement I have create PR first in the SDK and then after that get's merged I have to create a PR here.

Also I will come up with this in the meeting  for further doubts just clear me with these so I can start working 
and also if there is something I am missing please tell

**Comment by aaronreed708** [comment]
@omesh-omg those are all good questions.  The more I look at Image List, I'm thinking that this shouldn't be in the `Molecules` tab but rather in the `Components` tab.  If it is a component, then there is no corresponding SDK change.  I don't know of any accessibility-type property that could be applied to an image list except maybe border radius?  If it were a component then all we'd need to do, I would think, is display an image list (or variants of an image lists) on a light or dark mode background (depending on what the user selects) and make sure that it is appropriately styled and themed (e.g. title text has correct color and typography).

Am I understanding this correctly @lwnoble?  Or did you have a reason that you wanted it to be a molecule?

**Comment by omesh-omg** [comment]
Issue is resolved, branch merged successfully, therefore closing the issue.
