### ISSUE TITLE
Failure ui build

### ISSUE THREAD

**Issue by corners2wall** [finos/a11y-theme-builder#525]
## Problem/Concern
When I wanna try build ui I get next throw: 

![image](https://github.com/discoverfinancial/a11y-theme-builder/assets/110557519/166af423-827a-477f-83ab-d4af1ae819a6)

**Comment by smithbk** [comment]
@corners2wall Artem, this should be fixed now.  Please confirm.

**Comment by corners2wall** [comment]
@smithbk good job
