### ISSUE TITLE
[REQUEST] Design UX for changing a color

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#529]
## Suggestion/Concern

Currently it isn't possible in Theme Builder to change a color in a color palette.  Only new colors can be added.  One of the reasons for the current limitation is the fallout that would happen due to a change and the fallout may not be completely managed without human intervention.  For example, what happens to all of the molecules that were already using the original color?  What if the original color was the primary, secondary or tertiary color defined in the default color theme?  Which other default color theme values would be impacted?  Which atoms depend on the affected color theme?  Which "on" colors would need to be recalculated?  The goal of this issue is to design how a color change could be made by the user, how the application would communicate the impending issues to the user, what default values could be used until the user makes the manual updates, how is the user made aware of what manual updates need to be made, etc

**Comment by aaronreed708** [comment]
Related to #664

**Comment by msdorothyewuah** [comment]
Will be working on this issue.

**Comment by aaronreed708** [comment]
I believe that this issue was probably accomplished in the effort for https://github.com/finos/a11y-theme-builder/issues/738.  Do you agree @lwnoble?  If so, I think that we can close.

**Comment by aaronreed708** [comment]
@lwnoble agrees that this is accomplished in #738.  So closing.
