### ISSUE TITLE
Dark Mode Elevation Backgrounds

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#54]
## Dark Mode Elevation Backgrounds

* [link to problem content]()

## Proposed Solution
We need to pass a variable for the dark mode elevation background color for each molecule with an elevation:
i.e.  so for example card will need a variable like - dm-card-elevation-bg and to update the css with  "var(--elevation-bg-1)" and for the JSON will can just pass along a value from 0-9.

**Comment by aaronreed708** [comment]
This is an old issue.  Is this still a problem @lwnoble?

**Comment by aaronreed708** [comment]
This is being addressed in #803.  Closing per @lwnoble.
