### ISSUE TITLE
[Request] List of themes formating

### ISSUE THREAD

**Issue by Chessel** [finos/a11y-theme-builder#540]
## Problem/Concern
On your design system tab the theme cards are presented without any horizontal spacing.
The themes with long names (seem to happen only with very long words and not with titles with spaces between regular size words) push the "more button" outside the visible area of the card therefore not allowing the user to access the menu for that specific theme.
* [link to problem content]()
<img width="1553" alt="Screen Shot 2023-09-08 at 1 29 55 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/8109233/0fd38ca8-119c-456c-ae86-06071d14b2de">

## Proposed Solution

- Add margins to the theme's card
- wrap theme title text or concatenate it.

**Comment by aditiintechk** [comment]
Hi, I tried to fork and reproduce the issue but I do not see anything under 'Your Design Systems' section. Is it getting affected by any other component? Please let me know. Thanks.

**Comment by Chessel** [comment]
You'll need to create a couple of design systems for them to show under that section. When creating a design system try adding at least one with a very long title.

**Comment by aaronreed708** [comment]
@Aditi002-holo how did you start Theme Builder?  Are you using the instructions in: https://github.com/discoverfinancial/a11y-theme-builder/blob/main/DEV_GUIDE.md?  Are you using docker or npm?  Whichever way you use to start the server, after starting the server, go to http://localhost:3001 in a local browser and you should see a variety of default themes under the "Sample an Template Design Systems" and "Your Design Systems" sections.  The only times that I've noticed that those two sections are empty is if my server has been stopped.

If you'd like help to work out this issue, feel free to also contact us using one of these methods: https://github.com/discoverfinancial/a11y-theme-builder/wiki/Communication

**Comment by aditiintechk** [comment]
Hey, Aaron! I am using npm and I did see an error while running but let me try to run it again today. Okay, I will connect with you guys soon. Thanks.

**Comment by bsteffl** [comment]
I think this is already fixed.

**Comment by aaronreed708** [comment]
@bsteffl Thank you for noticing that!  @Chessel please reopen if you can re-create, but probably fixed in the round of changes we made prior to Grace Hopper.  Closing.
