### ISSUE TITLE
[Request] Fixed top header disappears

### ISSUE THREAD

**Issue by Chessel** [finos/a11y-theme-builder#543]
## Problem/Concern
There is a weird bug that allows the fixed top header to disappear if the user scrolls while cursor over the header. Then once the user wants to save the changes they have to scroll all the way up
* [link to problem content]()
<img width="1773" alt="Screen Shot 2023-09-08 at 2 17 24 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/8109233/bd08b57c-f54e-4bf6-b50e-6b9a9af40e99">

## Proposed Solution
- fix bug

**Comment by msdorothyewuah** [comment]
Hi @Chessel, I can't seem to be able to recreate the bug as the header works fine for me. Could you give me more context?

**Comment by Chessel** [comment]
@Turntabl-DorothyEwuah you are right I cannot reproduce this issue anymore. It might've been fixed!

**Comment by aaronreed708** [comment]
@Chessel said that this issue no longer exists, closing.
