### ISSUE TITLE
[TB] Global font weight settings not getting passed to individual font settings

### ISSUE THREAD

**Issue by Chessel** [finos/a11y-theme-builder#546]
## Problem/Concern
It seems like the font weight selected at the font Settings step are not getting passed to the body styles.
For example I set my Font weight 1 For standard body text. at 400 but when I get to the Body Style sections the weights don't seem to match to the individual body style settings they all seem to bolded.
* [link to problem content]()
<img width="503" alt="Screen Shot 2023-09-08 at 2 56 31 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/8109233/f76ad021-eb5d-4c76-9a47-13781749ccbf">
<img width="1079" alt="Screen Shot 2023-09-08 at 2 56 18 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/8109233/54809a66-19f4-4356-a5ba-3b5f87a49d1d">

**Comment by aaronreed708** [comment]
Fixed per @lwnoble.  @Chessel please verify.

**Comment by evangk6** [comment]
Will Verify - I believe this was fixed for GH Conference in mid-September

**Comment by Chessel** [comment]
This has been fixed!
