### ISSUE TITLE
[TB] Font Weight issues

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#563]
## Problem/Concern

1.) Currently, the font weights are associated with the secondary Font rather than the primary font.
2.) We need a drop down field that allows the user to pick the available font weight for the header (the Secondary font)
(I am askign Keith to add a SDK variable --headerWeight
3.) Can we update the default line height for small text to 16px?

**Comment by evangk6** [comment]
Looking at the code, it appears that the five fontweight selectables are changing the correct properties in the SDK. The issue appears to be how these properties are used. As Lise said, I don't see these changing the appearance for the Primary Font examples.

**Comment by evangk6** [comment]
@lwnoble  - to clarify point 2 in the description: We want the five fontweight selectables to effect the primary font, and a new 6th dropdown that effects header weight? What would this mean for fontweight 2 which is described as `For headers and small text that is important.`?

**Comment by lwnoble** [comment]
<img width="460" alt="Screenshot 2023-09-19 at 3 19 11 PM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/fcb54118-9280-48db-978d-58aa12766d91">

**Comment by evangk6** [comment]
waiting on @smithbk to add the secondary fontweight property in the SDK then the above will be a quick addition

**Comment by evangk6** [comment]
The 6th drop down is present and the default line height mentioned is changed.

**As for the Font Weight problem:**
We can see that the SDK is working and that the css variables are changing correctly. The problem appears to be how they are being used. Looking at the code I don't see them being used.

For example, changing the fontWeight1 dropwdown changes the `--fontWeight-1` variable which should effect all body1 text, but it doesn't change. Instead, the variable `--body1FontWeight` is used, which appears to not be calculated from fontWeight1.

@lwnoble - the question for you: Should changing these fontweight dropdowns directly change the typography styles for the classes? For example, changing fontWeight1, will automatically change the fontweight for body styles 1-3.

I went ahead and created a PR for this change so it is ready to go once you say so
https://github.com/discoverfinancial/a11y-theme-builder/pull/596/files

The logic is below, please confirm if this is the way it should work:
`fontweight0` -> caption, cta, small
`fontweight1` -> body
`fontweight2` -> labels, subtitles, overlines, caption bold, small semibold
`fontweight3` -> body bold
`fontweight4` -> stat

**Comment by evangk6** [comment]
this code has been merged

**Comment by evangk6** [comment]
Changes are in and appear to have the desired fix. However, we should investigate why the fontweights 0-4 have been changed to `unset` somewhere along the dev process.

**Comment by evangk6** [comment]
The font weight defaults have been changed to 300,400,600,700,800.
Note the sample design system has not changed.

**Comment by aaronreed708** [comment]
@lwnoble is ok with closing w/o sample updates.  Closing.
