### ISSUE TITLE
[TB] Dark mode issues

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#579]
## Problem/Concern

There are sections that have issues with dark mode.  Some of these are likely because we are no longer keying off of the .darkmode classname, but rather data-mode="dark" and data-mode="light".  A lot of black on black text.

These components are having issues with dark mode:

- Tabs secondary
- Tabs primary
- Switch
- Sliders
- Radio Buttons
- Lists - Single, Double, Triple
- Menus - are dropdown menus supposed to be white or dark?
- Hero
- Dropdowns - are dropdown menus supposed to be white or dark?
- Divider
- Chips
- Checkboxes
- Cards - can't see radio buttons on all of these card-related pages
- Avatars with icons
- App Bar - radio buttons
- Accordions - are the accordions supposed to be white?

Shadows - they are all broken

Colors
- Hotlinks - Dark Hotlinks don't match RGB values
- State Colors - not using --dm-success, --dm-* for the colors
- Gradients - not using --dm-* gradients
- Backgrounds - not using --dm-* backgrounds
- Core Colors - white, white-half and black-half are probably all wrong.  Maybe others.

Atoms
- Color Palette and Color Theme atoms have dark mode sections which aren't currently working.
- Shadow->Elevation Settings dark mode section not working
- State Settings
- Focus States
- Hotlinks
- Input Background
-

**Comment by aaronreed708** [comment]
In latest code there are still issues with:

**Components:**

Radio Buttons component
Divider component - vertical divider very faint in dark mode
Chips - can't see close buttons, very dark on a dark background
Checkboxes component
Shadows category - glow, elevations components still have problems
Colors category - hotlinks component - dark hotlinks colors seem wrong, don't match
Colors category - Core Colors component - white half and black half colors seem incorrect

**Atoms:**

Color Palette - dark mode colors and light mode colors sections need separation
Shadows Atoms - Elevation Settings - styling seems correct, but so hard to see the sample area border that it is difficult to see the subtle shifts for each elevation level
Hotlinks - dark mode colors and light mode colors sections need separation
Input Background - dark mode colors and light mode colors sections need separation, input disabled text is very dark and hard to see

**Comment by aaronreed708** [comment]
@lwnoble to review.  She believes may already be resolved.

**Comment by evangk6** [comment]
Opened https://github.com/finos/a11y-theme-builder/issues/743 as a good first issue to verify
