### ISSUE TITLE
[TB] Left Nav issues

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#583]
## Problem/Concern

The Left Nav no longer highlights the currently selected item.  Also, under Organisms, most of the items in the left nav have dividers between them.

**Comment by aaronreed708** [comment]
In latest code, selection now shows on hover, but doesn't remain after user clicks on left nav item.  Most of items in Left Nav under Organisms tab have dividers between them

**Comment by aaronreed708** [comment]
It looks like the problem with the left nav menu is because the right panel is taking the focus when the component is loaded in and when the left nav loses focus, the currently selected item is lost.  This did not happen previously, so it is something new.  If you click on the left menu item and the focus remains there, then the item will stay selected.

**Comment by aaronreed708** [comment]
So the change that broke left nav selection was in: https://github.com/discoverfinancial/a11y-theme-builder/commit/231da5b2367055aff65024c1871424fc66382cc0.  Looks like the var(--dropdown-focus-bg) in LeftNavTabs.tsx was removed.  I'll check with @lwnoble as to why.

**Comment by lwnoble** [comment]
So we should be able to achieve the same thing with a border - which is consistent with the figma file.  I have made the changes and updated the css.
