### ISSUE TITLE
[SDK] remove unnecessary radius and border styles

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#585]
## Problem/Concern

We can remove these from the border atom b/c the values are calculated in the css and figma:

--radius-0
--radius-2 | calc(var(--radius-1) * 2) | Radius x 2
--radius-3 | calc(var(--radius-1) * 3) | Radius x 3
--radius-4 | calc(var(--radius-1) * 4) | Radius x 4
--radius-5 | calc(var(--radius-1) * 5) | Radius x 5
--radius-6 | calc(var(--radius-1) * 6) | Radius x 6
--radius-7 | calc(var(--radius-1) * 7) | Radius x 7
--radius-8 | calc(var(--radius-1) * 8) | Radius x 8
--radius-9 | calc(var(--radius-1) * 9) | Radius x 9
--radius-10 | calc(var(--radius-1) * 10) | Radius x 10
--radius-quarter | calc(var(--radius-1) / 4) | Radius / 4
--radius-half | calc(var(--radius-1) / 2) | Radius / 2
--border-0
--border-2 | calc(var(--border-1) * 2) | Border x 2
--border-3 | calc(var(--border-1) * 3) | Border x 3
--border-4 | calc(var(--border-1) * 4)

<br class="Apple-interchange-newline">

* [link to problem content]()

**Comment by smithbk** [comment]
Lise, if we do all of these calculations in the CSS and Figma, then how is
that going to work for a use case in which they use only the SDK to
generate automated output?

**Comment by aaronreed708** [comment]
Fixed in latest code per @lwnoble and @smithbk
