### ISSUE TITLE
[SDK] JSON Code Bugs

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#588]
## Problem/Concern

The following needs updating:
1.)
As IS:
"Solid-Backgrounds": {
    "Primary": {
      "Color": {
        "type": "color",
        "value": "{Core-Colors.White.Color}"
      },
      "On-Color": {
        "type": "color",
        _**"value": "{Theme-Colors.Primary.On-Color.Half}"**_
      }
    },

Should be:
"Solid-Backgrounds": {
    "Primary": {
      "Color": {
        "type": "color",
        "value": "{Core-Colors.White.Color}"
      },
      "On-Color": {
        "type": "color",
        _**"value": "--on-background"**_
      }
    },

2.)
As Is:
"Solid-Backgrounds": {
    "Secondary": {
      "Color": {
        "type": "color",
        "value": "{Core-Colors.Gray.Color.050}"
      },
      "On-Color": {
        "type": "color",
        "value": "**_{Theme-Colors.Primary.On-Color.Quarter}_**"
      }
    },
},
Should be:

"Solid-Backgrounds": {
    "Secondary": {
      "Color": {
        "type": "color",
        "value": "{Core-Colors.Gray.Color.050}"
      },
      "On-Color": {
        "type": "color",
         **_"value":  --on-background-secondary_** 
      }
    },
},

3.)  Please update:
As Is: 
"Solid-Backgrounds": {
    "Tertiary": {
      "Color": {
        "type": "color",
        "value": "{Theme-Colors.Primary.Color.700}"
      },
      "On-Color": {
        "type": "color",
        "value": "{Text.White}"
      },
      **_"Button": {
        "type": "color",
        "value": "{Buttons.White.Color}"
      },
      "On-Button": {
        "type": "color",
        "value": "{Buttons.White.On-Color}"
      },
      "Icon": {
        "type": "color",
        "value": "{Icons.White.Color}"
      },
      "Hotlink": {
        "type": "color",
        "value": "{Hotlinks.White.Link}"
      }_**
    },
},
       
Should be:
"Solid-Backgrounds": {
    "Tertiary": {
      "Color": {
        "type": "color",
        "value": "{Theme-Colors.Primary.Color.700}"
      },
      "On-Color": {
        "type": "color",
        "value": "{Text.White}"
      },
    },
},
       

* [link to problem content]()

**Comment by aaronreed708** [comment]
issues fixed in latest code per @lwnoble
