### ISSUE TITLE
[TB] Button Height needs to offer sizes down to the selected min target

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#598]
## Problem/Concern

If a user says the min height is 32px they should be able to select a button height of 32px or 40px.

If a user says 24px then they can go as low as 24px but now we only have as low as 32px.

* [link to problem content]()

**Comment by aaronreed708** [comment]
related to #601

**Comment by evangk6** [comment]
Added description to #601 as this is possible a duplicate
