### ISSUE TITLE
[TB] Add Mobile/Table Target and provide additional height as options in dropdown

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#600]
## Proposed Solution
<img width="630" alt="Screenshot 2023-09-20 at 11 32 11 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/d9ed0013-359d-4b7a-abbb-d836a31792f9">

Please offer the following options available in both drop downs:

<img width="213" alt="Screenshot 2023-09-20 at 11 34 23 AM" src="https://github.com/discoverfinancial/a11y-theme-builder/assets/6164440/781ad17b-d26a-4af3-8f30-75f2051ac46c">

Note those values are using the grid value of 
3 x grid (8 or 10)
4 x grid (8 or 10)
5 x grid (8 or 10)
6 x grid (8 or 10)
7 x grid (8 or 10)
and 44 (apple target area)
and 48 (android target area)

**Comment by evangk6** [comment]
change is in
