### ISSUE TITLE
[TB] Theme Layers dropdown styling needs improvement

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#619]
## Problem/Concern

There is something funky going on with the CSS for the Theme Layers dropdown.  Selected radio buttons under "Devices" menu item don't show the radio button part, just the dot indicating selection.  The style in Theme.css that seems to be causing the problem is:
```
.MuiMenuItem-root, .MuiMenuItem-root .MuiSvgIcon-root{
  background: var(--surface);
  color: var(--on-surface);
}
```

The background: var(--surface) is messing up the SVG of the radio button and causing the fill not to work.  Removing that line fixes the problem.  But I haven't figured out what removing this may affect, yet.

In general the styling for the dropdown could be improved.  It seems very clunky/blocky to me.

**Comment by skaushik16** [comment]
Taking a look at this (part of GHC 23)

**Comment by aaronreed708** [comment]
Hi @skaushik16!  I just wanted to reach out and offer any assistance or guidance that you may need as you look at this issue.  We are happy to help!

**Comment by aaronreed708** [comment]
Hi @skaushik16, I just wanted to reach out one more time to see if you need any help making progress on your contribution.  You can respond to me here or you can reach out to me directly on Slack.  More information on communicating with the Theme Builder community can be found here: https://github.com/finos/a11y-theme-builder/wiki/Communication#communication-channels.  I hope to hear from you soon!

**Comment by aaronreed708** [comment]
No feedback from contributor, returning to the pool

**Comment by msdorothyewuah** [comment]
I am looking into this issue as a good first issue to contribute to

**Comment by msdorothyewuah** [comment]
@aaronreed708 could you help me with more information for this issue as per the screenshot below the radio button seems to fill out correctly. Please let me know if there is anything I am missing. 

![Image](https://github.com/finos/a11y-theme-builder/assets/149516919/9e3e9507-82ef-4d1b-8a91-ad2a2755e0ef)

**Comment by aaronreed708** [comment]
Hi @Turntabl-DorothyEwuah, I believe that this has been fixed somewhere along the way since I opened it.  I'm guessing that @lwnoble probably fixed it before one of her presentations and just forgot to close this issue.  It looks good to me now.  You can close this issue if you also don't see any issues

**Comment by aaronreed708** [comment]
Closing as fixed
