### ISSUE TITLE
[SDK] Sending wrong On Button on Tertiary 

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#621]
## Problem/Concern

In the JSON The Tertiary Button and Tertiary On Button Tertiary  are the same color

I think the Tertiary Button Color is wrong

* [link to problem content]()

**Comment by smithbk** [comment]
@lwnoble Is this is the base, lightmode, and/or darkmode JSON?
Please provide full path to these variables.

**Comment by smithbk** [comment]
Lise said is not a problem in JSON code
