### ISSUE TITLE
[SDK] The JSON Base Code is not sending the proper boolean values for colors

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#628]
## Problem/Concern

Currently for all the colors we are passing true.

The color-2 should be true if the user has selected a 2nd color.  But if they do not it should be false.  This allows us to show/hide colors in figma.  If we don't hide the unused colors they see colors in their theme that they did not add.

* [link to problem content]()

**Comment by smithbk** [comment]
In Show-Colors in base JSON, the secondary should be false if it is the same as the primary,
and tertiary should be false if the same as the primary or secondary

**Comment by smithbk** [comment]
@lwnoble Fixed, merged.  Please verify.
