### ISSUE TITLE
[TB] Add scope to FINOS TB packages

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#639]
## Problem/Concern

We need to add scope to the Theme Builder and Theme Builder SDK packages for FINOS.  FINOS requested that "@finos/" be prepended to package names.

This probably needs to wait until the SDK can be updated on npm in the FINOS org

**Comment by aaronreed708** [comment]
Depends on #640

**Comment by aaronreed708** [comment]
Code has been committed to dev and tested.  PR for updating main from dev was failing a CVE check, so will fix that (https://github.com/finos/a11y-theme-builder/issues/710) prior to moving dev to main.

**Comment by PaulaPaul** [comment]
Closed at project call
