### ISSUE TITLE
[TB] Light mode chip & on-chip colors

### ISSUE THREAD

**Issue by brycecurtis** [finos/a11y-theme-builder#64]
## Problem/Concern

Fix the light mode --chip and --on-chip colors based upon calculations.

**Comment by brycecurtis** [comment]
Look at the $('#addTheme').click(function() function in Lise's js file for the calculation.

**Comment by smithbk** [comment]
I saw something wrong with the --on-chip calculation but not the --chip.  I was already following the logic for that from the addTheme callback function.  So I need more info on what exactly is wrong with the --chip value in light mode.
