### ISSUE TITLE
[SDK] Publish SDK to FINOS npm org with scope

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#640]
## Problem/Concern

We need to update the SDK published to npm so that it is in the FINOS org and scoped as "@finos/a11y-theme-builder-sdk".  We'll need to get with the FINOS team to get this done.

**Comment by aaronreed708** [comment]
Juan gave this response, re: npm publishing, in an email:

_Regarding NPM the updates can happen via GitHub Action or manually (the common approach is to automate it), the choice is yours. You can see an example of a GitHub Action here https://github.com/finos/git-proxy/blob/main/.github/workflows/npm.yml. And we can set the NPM_TOKEN on the repo._ 

_As for updating the scopes, the sooner the better, but best effort there is no deadline._

When I was publishing stuff to NPM  in a previous job, I always published manually or used automation with a trigger on it (via Travis) when I tagged the repo, just for the control aspect.  It had to be a conscious decision.  @smithbk do you have an opinion?  I wouldn't mind automation, perhaps, if we can make it trigger due to a tag or something similar.

**Comment by smithbk** [comment]
@aaronreed708 I don't think we want to trigger an npm publish with every checkin.  The way we did it before was that we had a dev and prod/main branch in our CI/CD pipeline.  We check into the dev branch often but promote to main less often.  The npm publish would happen with each promotion to the main branch.

**Comment by aaronreed708** [comment]
Discussed with @smithbk today.  We'd like to:

- change scope "@finos/a11y-theme-builder-sdk"
- change version to 1.0.0
- automatically increment versions with GitHub actions
  - should only update minor versions.  Major versions should be manually updated.
- Keith will deprecate previous package

**Comment by aaronreed708** [comment]
Pushed to dev today.  Will leave open until pushed to main to make sure Theme Builder is ready to use it

**Comment by aaronreed708** [comment]
Pushed to main today and working.  I had to comment out the instructions in the workflow for bumping the npm version number of the package since the `git push` was failing (need to have a PR to commit to main under FINOS).  I will see if I can figure out a way to work around this.

**Comment by PaulaPaul** [comment]
Closed at Project meeting
