### ISSUE TITLE
[SDK] Regenerate Swagger documentation for FINOS

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#646]
## Problem/Concern

There are a lot of files committed to the SDK that still have "github.com/discoverfinancial" in them.  Now that the SDK has been transferred to FINOS, these files need to be corrected.  They live in the /docs/interfaces and /docs/classes directories and /docs/index.html.  Keith believes that these are auto generated as Swagger docs.  So this issue is to get those files re-generated and committed.

**Comment by smithbk** [comment]
@aaronreed708 See PR https://github.com/finos/a11y-theme-builder-sdk/pull/116.  Not sure why there are merge conflicts.  Could you check?

**Comment by smithbk** [comment]
BTW, `npm run build` from the root of this repo regens these files.  There were also a couple of places in the README.md that also needed manually updating.

**Comment by aaronreed708** [comment]
@smithbk fixed in https://github.com/finos/a11y-theme-builder-sdk/commit/ca543d1454b4afbc5d968dcfeddecb275be817ee.  Closing.
