### ISSUE TITLE
[SDK] Formatting of shadow info passed in JSON is incorrect

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#649]
## Problem/Concern

We are currently passing the shadow info as:

 "Shadows": {
    "Button-Shadow": {
      "type": "boxShadow",
      "value": "Elevation-3"
    },
    "Chip-Shadow": {
      "type": "boxShadow",
      "value": "Elevation-2"
    },
    "Avatar-Shadow": {
      "type": "boxShadow"
    },
    "Card-Shadow": {
      "type": "boxShadow"
    },
    "Image-Shadow": {
      "type": "boxShadow"
    },
    "SliderHandle-Shadow": {
      "type": "boxShadow",
      "value": "Ridge-3"
    },
    "SliderBar-Shadow": {
      "type": "boxShadow",
      "value": "Ridge-3"
    },
    "Modal-Shadow": {
      "type": "boxShadow"
    },
    "Tooltip-Shadow": {
      "type": "boxShadow"
    },
    "Toast-Shadow": {
      "type": "boxShadow"
    },
    "Dropdown-Shadow": {
      "type": "boxShadow",
      "value": "Elevation-1"
    }
  },

It Should be:
 "Shadows": {
    "Button-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-3}"
    },
    "Chip-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-2}"
    },
    "Avatar-Shadow": {
      "type": "boxShadow"
    },
    "Card-Shadow": {
      "type": "boxShadow"
    },
    "Image-Shadow": {
      "type": "boxShadow"
    },
    "SliderHandle-Shadow": {
      "type": "boxShadow",
      "value": "{Ridges.ridge-3}"
    },
    "SliderBar-Shadow": {
      "type": "boxShadow",
      "value": "{Ridges.ridge-3}"
    },
    "Modal-Shadow": {
      "type": "boxShadow"
    },
    "Tooltip-Shadow": {
      "type": "boxShadow"
    },
    "Toast-Shadow": {
      "type": "boxShadow"
    },
    "Dropdown-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-1}"
    }
  },

We are passing along other variables; hence the shadows need to be wrapped in '{}' curly brackets.

Each of the shadows has a prefix.  The available prefixes are:

Elevation-Shadows
Bevels
Inverted-Bevels
Grooves
Ridges
Recesses
Glow-Shadows

and then all the names are lowercase such as:
elevation-0
bevel-1
inverted-bevels-1
groove-1
ridge-1
recess-1
glow-1

* [link to problem content]()

**Comment by smithbk** [comment]
@lwnoble Fixed and merged ... please verify
