### ISSUE TITLE
[TB] Deploy Theme Builder through FINOS

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#651]
## Problem/Concern

We currently have a version of Theme Builder, using local storage for storing themes, running on Netlify (https://main--loquacious-biscuit-2083c6.netlify.app/).  This issue is to track the effort to achieve the same ends using FINOS infrastructure.  @maoo said that FINOS usually achieves this using GitHub actions to deploy the static content.

**Comment by aaronreed708** [comment]
If possible, we should achieve this by All Things Open, to further emphasize that we are a FINOS project.

**Comment by maoo** [comment]
Hi @aaronreed708 ! I've configured Netlify as follows....

<img width="484" alt="netlify-config" src="https://github.com/finos/a11y-theme-builder/assets/327285/3f2dc6fd-7f87-457e-998e-60f5e3f77f19">

However the build fails, I've uploaded logs on https://gist.github.com/maoo/fdb1867297c232da50f4cd5d81b97302

Note that Node version is v18.18.0 (npm v9.8.1) - see https://gist.github.com/maoo/fdb1867297c232da50f4cd5d81b97302#file-gistfile1-txt-L19

Could you try to reproduce the issue using your personal (free) Netlify account?

**Comment by aaronreed708** [comment]
Hey Mao, it looks like the issue are these lines in the log:

_10:15:41 AM: Treating warnings as errors because process.env.CI = true.
10:15:41 AM: Most CI servers set it automatically.
10:15:41 AM: 
10:15:41 AM: Failed to compile._

I'm guessing that this is because of a difference in your configuration vs ours?  I don't own our deployment, and Bryce is on vacation until Monday.  I'll try to see if I can get this running tonight without these errors.

**Comment by aaronreed708** [comment]
https://stackoverflow.com/questions/62663451/treating-warnings-as-errors-because-process-env-ci-true-failed-to-compile has a post about how to turn off CI env var on Netlify.

Does CI need to be on for FINOS or is this something we can turn off until we fix the warnings?

**Comment by maoo** [comment]
@aaronreed708 - we can probably set environment variables at build level, should not be a problem.

Before trying different options on our build, I'd ask you to reproduce the issue on your own Netlify free account, which is free for open source projects.

Could you please sign up to netlify.com, import the project from GitHub and configure the build as mentioned above?

This would allow you to tweak the build as needed and find the right configuration that works for your project. At that point I'll just have to copy your settings.

Please let me know if you have problems with this approach, thanks!

**Comment by aaronreed708** [comment]
@maoo I signed up for Netlify and tried to deploy my github repo.  It failed with the same build issue you saw.  I added CI=false to the environment and that fixed the build issue.  I then tried to import a design system from my laptop and it failed.  So I had to also set REACT_APP_STORAGE=local and now everything works well and I can import and save design systems.  So please set these in your Netlify environment:

CI=false
REACT_APP_STORAGE=local

**Comment by maoo** [comment]
Thank you @aaronreed708 , that worked! Please access the deployment on https://main--dapper-ganache-45a60b.netlify.app/

Which CNAME shall we use for this website? What about `try.a11y-theme-builder.finos.org` ?

**Comment by aaronreed708** [comment]
Hi @maoo, we are good with try.a11y-theme-builder.finos.org.  Thanks!

**Comment by maoo** [comment]
> Hi @maoo, we are good with try.a11y-theme-builder.finos.org. Thanks!

@aaronreed708 , it's done! http://try.a11y-theme-builder.finos.org/ - it may take few more minutes to enforce https

Feel free to close the issue if you there's nothing else pending.

**Comment by aaronreed708** [comment]
Worked for me, closing.
