### ISSUE TITLE
[SDK] SDK sending Button Color Unknown in dark mode

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#655]
## Problem/Concern

"Buttons": {
    "Colored": {
      "Color": {
        "type": "color",
        "value": "{Theme-Colors.Secondary.Color.unknown}"
      },
      "On-Color": {
        "type": "color",
        "value": "{Theme-Colors.Secondary.On-Color.unknown}"
      },
      "Color-Half": {
        "type": "color",
        "value": "{Buttons.Colored.Color}80"
      }
    },

**Comment by smithbk** [comment]
@lwnode This should be fixed in latest.  Please confirm.
