### ISSUE TITLE
[SDK] Font weights being for the primary font is being passed as 0 for all font-weight-0 through  font-weight-4

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#668]
## Problem/Concern

  "fontWeights": {
    "font-weight-0": {
      "type": "fontWeights",
      "value": "0"
    },
    "font-weight-1": {
      "type": "fontWeights",
      "value": "0"
    },
    "font-weight-2": {
      "type": "fontWeights",
      "value": "0"
    },
    "font-weight-3": {
      "type": "fontWeights",
      "value": "0"
    },
    "font-weight-4": {
      "type": "fontWeights",
      "value": "0"
    },
    "secondary-font-weight": {
      "type": "fontWeights",
      "value": "400"
    },

**Comment by evangk6** [comment]
I can confirm that these values are set to 0 in the sample system. When you create a new design system, the default values take effect, and can be seen correctly.

![image](https://github.com/finos/a11y-theme-builder/assets/36457549/e5f4d4b7-a815-4675-ad3e-0fb60f28ef1d)

@lwnoble  - To complete this issue, would you simply like me to change the fontWeight values in the sample system or leave them as they are?

**Comment by evangk6** [comment]
assuming so @brycecurtis - what is the correct way to update sample values? Should I simply change the `themes.json`?

**Comment by brycecurtis** [comment]
@evangk6 Editing the database file has been problematic, so it's best to edit the sample design system using Theme Builder, save it, exit Theme Builder, then check in the resulting data/themes file.

**Comment by evangk6** [comment]
I updated the sample systems in https://github.com/finos/a11y-theme-builder/pull/705.
