### ISSUE TITLE
[SDK] JSON Shadows not formatted correctly

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#675]
## Problem/Concern

The Base JSON Code which renders the shadows, is not formatting the shadow variables correctly.

## Proposed Solution
As is:
  "Shadows": {
    "Button-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows-elevation-2}"
    },
    "Chip-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows-elevation-2}"
    },
    "Avatar-Shadow": {
      "type": "boxShadow"
    },
    "Card-Shadow": {
      "type": "boxShadow"
    },
    "Image-Shadow": {
      "type": "boxShadow"
    },
    "SliderHandle-Shadow": {
      "type": "boxShadow"
    },
    "SliderBar-Shadow": {
      "type": "boxShadow"
    },
    "Modal-Shadow": {
      "type": "boxShadow"
    },
    "Tooltip-Shadow": {
      "type": "boxShadow"
    },
    "Toast-Shadow": {
      "type": "boxShadow"
    },
    "Dropdown-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows-elevation-1}"
    }
  },

Should Be
  "Shadows": {
    "Button-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-2}"
    },
    "Chip-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-2}"
    },
    "Avatar-Shadow": {
      "type": "boxShadow"
    },
    "Card-Shadow": {
      "type": "boxShadow"
    },
    "Image-Shadow": {
      "type": "boxShadow"
    },
    "SliderHandle-Shadow": {
      "type": "boxShadow"
    },
    "SliderBar-Shadow": {
      "type": "boxShadow"
    },
    "Modal-Shadow": {
      "type": "boxShadow"
    },
    "Tooltip-Shadow": {
      "type": "boxShadow"
    },
    "Toast-Shadow": {
      "type": "boxShadow"
    },
    "Dropdown-Shadow": {
      "type": "boxShadow",
      "value": "{Elevation-Shadows.elevation-1}"
    }
  },

Currently the code uses a "-" between the title of the shadow type and the title specific shadow type 1-9, but it should be using a "."

**Comment by smithbk** [comment]
Fixed.  Please verify.  Install latest SDK with 'install-sdk.sh'.  The npm module has not been updated.

**Comment by aaronreed708** [comment]
Close per @lwnoble
