### ISSUE TITLE
[TB] Entire design system card should be clickable with hover and focus states

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#676]
Currently, only part of the cards under "Your Design Systems" are clickable.  The entire card should be clickable with hover and focus states.

The button with the ellipsis should use stop propagation to prevent it from triggering the behavior associated with the entire card.

* [link to problem content]()

**Comment by Lovelyfin00** [comment]
Hi @lwnoble @PaulaPaul  @evangk6 @aaronreed708 
I'd like to work on this.
I just have some questions.

- Is the action on the `IconButton` going to be taken out and it's just going to remain there for looks purposes.
- Do you want the `MenuItem` to show to on hover or only on click?

**Comment by aaronreed708** [comment]
Hi @Lovelyfin00,

> * Is the action on the `IconButton` going to be taken out and it's just going to remain there for looks purposes.
> * Do you want the `MenuItem` to show to on hover or only on click?

So the desired behavior here is that the IconButton should continue to work as it does now.  Clicking on it should still display a popup menu with options that can be selected like "Load Design System".

The change is that the action of clicking on the card (anywhere other than the IconButton) should load the design system.  @lwnoble is also saying that the whole card should have hover and focus states just like IconButton does.

**Comment by Lovelyfin00** [comment]
> Hi @Lovelyfin00,
> 
> > * Is the action on the `IconButton` going to be taken out and it's just going to remain there for looks purposes.
> > * Do you want the `MenuItem` to show to on hover or only on click?
> 
> So the desired behavior here is that the IconButton should continue to work as it does now. Clicking on it should still display a popup menu with options that can be selected like "Load Design System".
> 
> The change is that the action of clicking on the card (anywhere other than the IconButton) should load the design system. @lwnoble is also saying that the whole card should have hover and focus states just like IconButton does.

Hi @aaronreed708 
Ok great
I understand what’s required now
Thank you😄

**Comment by aaronreed708** [comment]
@Lovelyfin00 PR works great!  Closing.
