### ISSUE TITLE
[TASK] Remove temporary repo that was used for Grace Hopper Celebration Open Source Day

### ISSUE THREAD

**Issue by PaulaPaul** [finos/a11y-theme-builder#682]
Tasks needed to clean up 'stray copies' of Theme Builder:

* Confirm any content that we'd like to preserve from the [GHC repo](https://github.com/nearform-oss/a11y-theme-builder) has been transferred to the FINOS repo
* Delete the GHC repo (@PaulaPaul or Cody Zuchlag can remove the GHC repo when ready)

**Comment by PaulaPaul** [comment]
Can someone confirm we no longer need the changes in these branches, which are not up to date with the FINOS repo? https://github.com/nearform-oss/a11y-theme-builder/tree/gh-pages
https://github.com/nearform-oss/a11y-theme-builder/tree/dev

These two repos have one commit ahead of the corresponding FINOS repo. I don't see anything in those commits that needs to be brought forward but wanted another set of eyes and confirmation before removing the GHC repo.

If I can get some 'thumbs up' or comments here to confirm, I'll remove the downstream and we can close this issue.

**Comment by aaronreed708** [comment]
@PaulaPaul I don't see anything in the NearForm repo that needs to be preserved.  I don't see any changes made by outside contributors and I don't see anything on the branches you mentioned above that should be kept that doesn't already exist in the FINOS repo.  Thank you for hosting the repo as long as you have!

**Comment by PaulaPaul** [comment]
The shadow repo used for Grace Hopper Open Source Day has been deleted and this issue can be closed.
