### ISSUE TITLE
[TB] Template scrolls out of frame

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#685]
## Problem/Concern

Click on the TEMPLATE nav item from the nav bar.
Size the browser window smaller than the size of the black frame in the Template pane holding the content of the sample page.
Scroll the browser window.

Notice that the content of the sample page and the pane background scrolls up but the black frame remains fixed.  So now the contents of the sample page are partially outside of the frame.

## Proposed Solution

The black frame should scroll with the panel background and not remain in a fixed position.

**Comment by aaronreed708** [comment]
Also notice at the bottom of the image that the light-yellow background is scrolled up so that the user can see the white behind itl.

**Comment by prithviraj-chaudhuri** [comment]
Looking at this issue as a potential first issue to contribute to this project

**Comment by aaronreed708** [comment]
Hi @prithviraj-chaudhuri, I noticed that you made a PR to do your Easy CLA, but it looks like you never completed the process.  I'm happy to help you get past this hurdle if you'd like.  Please let me know.

**Comment by prithviraj-chaudhuri** [comment]
Hi @aaronreed708 I was waiting for my employer to approve the ICLA, I will sign it and then create a PR for this fix. Thanks

**Comment by evangk6** [comment]
This needs to be reviewed to see if the issues has been fixed.

**Comment by aaronreed708** [comment]
It looks like this is fixed?  Contents don't scroll out of the black border anymore, but if the browser is sized smaller than the "computer" on the page (or the user zooms the page), there is no way for the user to scroll and see the bottom of the template because it is already scrolled to the end in the "computer", but the bottom edge of the "computer" is out of view.  Closing for now.  Will repopen if this behavior is deemed undesirable.
