### ISSUE TITLE
[TB] Font size slider issue

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#691]
## Problem/Concern

If you use the font slider and you create a font size larger than 128 we get an error.

<img width="1262" alt="Screenshot 2023-10-26 at 10 12 18 AM" src="https://github.com/finos/a11y-theme-builder/assets/6164440/f09daac2-65f0-4c78-8ffb-2687e9ae681d">

* [link to problem content]()

## Proposed Solution

We need to increase that range to [0-200]

**Comment by evangk6** [comment]
Pr is ready for review https://github.com/finos/a11y-theme-builder-sdk/pull/144

**Comment by aaronreed708** [comment]
@evangk6 is this issue complete?

**Comment by evangk6** [comment]
@aaronreed708 - The code is merged. I'll verify.

**Comment by evangk6** [comment]
Looks like this is working. The slider can now produce font sizes above 128 (up to 256) without errors.
![image](https://github.com/finos/a11y-theme-builder/assets/36457549/f83cda2a-258c-43c4-89f4-ff8650f58e62)
