### ISSUE TITLE
[TB] Update default bevel settings

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#692]
## Problem/Concern

* [link to problem content]()

## Proposed Solution
Can we please update the default settings to the following:

Light Glow 17
Dark Glow 10
Percentage Change 17

**Comment by omesh-omg** [comment]
hey @aaronreed708  @PaulaPaul  @lwnoble  can you assign this issue to me I want to get familiar with  theme builder SDK as well

**Comment by aaronreed708** [comment]
This has been merged.  Closing.
