### ISSUE TITLE
[TB] Deprecate old SDK in NPM

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#713]
## Problem/Concern

We need to properly deprecate the old a11y-theme-builder-sdk in NPM.  This issue is open to identify what needs to happen, what the end user will see/experience, and to complete this work.  But we should bring this issue up at the next community meeting on 11/9 before doing the work.

**Comment by PaulaPaul** [comment]
discussed at project call - no dissents

**Comment by aaronreed708** [comment]
Re-opening until the deprecation work is done.

**Comment by aaronreed708** [comment]
@smithbk deprecated previous SDK library on 11/16.  Closing issue.
