### ISSUE TITLE
[community] Form a community building working group

### ISSUE THREAD

**Issue by PaulaPaul** [finos/a11y-theme-builder#719]
During the project call on Nov 2 there was discussion of forming a working group to focus on community building, hackathons, and event participation, to grow the community of contributors and consumers of ally-theme-builder.

@PaulaPaul will set up time with @lwnoble, @codyzu and others interested in community activities, and open issues to update documentation and meeting notes for the working group goals and activities.

**Comment by PaulaPaul** [comment]
@aaronreed708 @brycecurtis @lwnoble I'm unable to create labels or assign issues (to myself, like this one) - could we create a label for 'community' so that I can track the working group items like this?
I would ideally like write access to the project in order to lead the working group activities and set up documentation - open for discussion on this week's project call. Thanks!

**Comment by aaronreed708** [comment]
@lwnoble also had this issue, but at the time she wasn't designated as a maintainer but I thought that you and Cody both were. Let me check with Juan.

**Comment by aaronreed708** [comment]
@PaulaPaul I sent a request to FINOS for you to be able to write to the repo and wiki, to be able to assign issues and to create labels.  I'll update this issue when I know more.

**Comment by aaronreed708** [comment]
@PaulaPaul, please try again.  You should have access now.

**Comment by PaulaPaul** [comment]
Confirmed access to create labels and assign myself issues!

**Comment by codyzu** [comment]
Love this idea

**Comment by PaulaPaul** [comment]
This issue was discussed during the Nov 30 project call - @codyzu, @lwnoble and @PaulaPaul will meet every two weeks to discuss community building and outreach efforts, and potential website uplift to attract and drive community engagement.
@PaulaPaul will schedule calls and explore ways to put those calls on the FINOS calendar-

**Comment by aaronreed708** [comment]
@aaronreed708 to add to FINOS calendar, get new FINOS zoom link?

Every 2 weeks on Wednesdays at 11am EST starting 1/17

**Comment by PaulaPaul** [comment]
Email has been sent to FINOS to make these meetings public on the FINOS Calendar - once we receive that information and zoom we can add the information to the Theme Builder FINOS website and close this issue- thanks @aaronreed708

**Comment by PaulaPaul** [comment]
We have Zoom credentials - will close out this issue once the regular community call is on the FINOS calendar- thank you!
@TheJuanAndOnly99 @aaronreed708

**Comment by PaulaPaul** [comment]
Confirmed our community calls are now on the FINOS calendar, and I am all set up with the Zoom credentials to host calls. Thank you @TheJuanAndOnly99 and @aaronreed708 !

Will close out this issue as complete -
