### ISSUE TITLE
[TB] Discuss possible GitHub security changes

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#722]
## Problem/Concern

Brought up as a concern at our community meeting two weeks ago, a community member suggested that we speak with FINOS and see if there is a way to prevent a contributor from create a PR against the "main" branch to prevent accidental commits to main now that dev is our default development branch.

Juan replied:

_I do not believe there is a setting for preventing pull requests from being created. However, I have enabled the following setting on the `main` branch "Restrict who can push to matching branches" and restricted it to the [maintainer team](https://github.com/orgs/finos/teams/a11y-theme-builder-maintainers)._

_We could limit this maintainers team to just 1 (or maybe 2) "release managers" and give everyone else on this team `write` access, preventing them from pushing to `main` due to the above rule but still allowing them to push to other branches_.

Mao replied:

_Agreed with Juan - there's no way to prevent PRs from being created; however, there may be few things that could be explored:_

_1. Make the dev branch the main one; this would make the dev branch the default one to raise PRs against
2. Investigate GitHub Apps to "flag" PRs raised to branches other than dev_

## Proposed Solution

I like Juan and Mao's suggestions, I am proposing that we:

1. change the default branch to dev to make things easier/less error prone for contributors creating PRs
2. create 1 or 2 release managers that are able to commit to main **OR** require PRs to main to be reviewed and approved by two other maintainers

**Comment by aaronreed708** [comment]
Discussed in today's call, we resolve to:

- Leave main as default branch
- Increase the number of reviews required for main commits to 2

**Comment by aaronreed708** [comment]
@TheJuanAndOnly99: can you please change the rules on a11y-theme-builder-sdk and a11y-theme-builder to only allow PRs to be committed to main after TWO reviews?

**Comment by TheJuanAndOnly99** [comment]
Hi @aaronreed708 ,

I've enabled the following branch protection rule on the `main` branch for both a11y-theme-builder-sdk and a11y-theme-builder:
![Screenshot 2023-11-17 104336](https://github.com/finos/a11y-theme-builder/assets/36825759/eca85038-82af-4c71-99ee-5a4ab4a4f1be)

**Comment by aaronreed708** [comment]
Thanks @TheJuanAndOnly99!  With this change I'll close this issue as resolved.
