### ISSUE TITLE
07 Dec 2023 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#740]
## Date
20231207 - 09:15am EST

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Accessibility Layer work is ongoing. For #397 Keith has some adjustments and Lise is implementing the front end wit the goal for next week.
- The Fidelity Meeting: Lise gave availability and we should hear back soon.
- https://github.com/finos/a11y-theme-builder/pull/733
- Lise to review: #601, #685
- Lise will schedule time with Aaron for #606 and other issues
- #544 discussion ongoing
- #686 waiting for Yessel
- #541 potentially assigned to Dorothy
- #719 Lise and Paula are continuing progress with community meetings
- #738 should have updates next week
- [#687](https://github.com/finos/a11y-theme-builder/issues/687#issuecomment-1845441227) Paula to create issue to obtain OpenSSF badge

**Comment by evangk6** [comment]
Evan K - DFS

**Comment by lwnoble** [comment]
Lise W Noble - DFS

**Comment by PaulaPaul** [comment]
Paula Paul - Greyshore Associates

**Comment by ronaldssebalamu** [comment]
Ronald Ssebalamu / FINOS

**Comment by msdorothyewuah** [comment]
Dorothy Ewuah - Turntabl

**Comment by aaronreed708** [comment]
Accepted in today's meeting.  Closing.
