### ISSUE TITLE
[TB] Do Design Thinking around displaying larger amounts of information to the user via the UI

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#752]
## Problem/Concern

Related to #750.

The goal of this issue is to do Design Thinking on how a user might best discover documentation-level information through the Theme Builder UI.  For example, WCAG 2.1 defines how a button color must contrast with the background color.  It also  specifies how how the color of anchor/link text must contrast with background colors AND the color of surrounding text.  And whether a link needs to be underlined is also affected by this specification.  So what is the best way to convey this information to the user and in what context in the UI.

We have already attempted this by adding "Note:" text to the Create Color Theme widget.  But these were short, one line blurbs.  The user may need the ability to find more detailed information and display it through the Theme Builder UI.  May need to be added throughout the UI (e.g. make available on atom and molecule pages).

**Comment by lwnoble** [comment]
See Figma File: https://www.figma.com/file/qplg5PqoDAK6dh9Y58JlMD/Building-Themes?type=design&mode=design&t=PUwaunPdRh9LHxLm-1

**Comment by evangk6** [comment]
Update from today's meeting: Lise finished, Yessel fine-tuning.

Need to assign Yessel, but can't - @aaronreed708

**Comment by aaronreed708** [comment]
@Chessel can you assign to yourself, please?

**Comment by Chessel** [comment]
I'll work on this!

**Comment by Chessel** [comment]
Question: @aaronreed708 I see that Lise has attached the Figma file of the new design for Theme Builder. Do we want to build this for the to-be stage or do we also need a solution that can be implemented with the as-is design?

If we need some design to implement with the as-is design can you @aaronreed708 provide a screenshot to see how we are solving this today? thanks

**Comment by aaronreed708** [comment]
@Chessel we probably need to talk with @lwnoble to see how she wants to stage the updates.  I would think, conceptually, that the documentation-based changes might be self-contained enough to be able to bring into the current code without depending on other changes having already been done.  But I honestly haven't reviewed much of the Figma, yet.

**Comment by Chessel** [comment]
Here is a good starting point to show large amounts of information while aligning with the upcoming UI changes. 

1. Well add a static right side bar titled A11y Rules
2. We show all the information related to WCAG that is relevant for that particular atom, molecule, component etc
3. We show that the current state meets/doesn't meet the rule by checking the checkbox
4. TBD How it looks like when the rule is not met? For starters unchecked checkbox, but do we need recommendations/other information?
![Issue 752](https://github.com/finos/a11y-theme-builder/assets/8109233/d3b4cf08-ab7c-4ebd-8511-fc108dd2832d)

**Comment by Chessel** [comment]
updated design
![Issue 752 (1)](https://github.com/finos/a11y-theme-builder/assets/8109233/fa09f17e-da96-4dc2-a0d3-a673e908ee36)

**Comment by evangk6** [comment]
@aaronreed708 - we believe this is complete, need an issue to implement

**Comment by aaronreed708** [comment]
> @aaronreed708 - we believe this is complete, need an issue to implement

This issue is tied to #753 .  Closing per @evangk6
