### ISSUE TITLE
[TB] Reconcile naming conventions between code and figma to enable exporting code properly

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#772]
## Problem/Concern

We have an incredible opportunity to streamline the design to the development process from Figma who's components, organisms, and templates are rendered using tokens by taking advantage of the [Anima figma plugin.](https://www.animaapp.com/figma)

## Proposed Solution

In order to get this working we need to reconcile the naming convention of components, organisms and css variables in both Figma and Theme Builder.

**Comment by aaronreed708** [comment]
Related to #806 #760

**Comment by evangk6** [comment]
Lise completed 0418
