### ISSUE TITLE
[Community] Abstract for GHC CFP - Community Presentation on Theme Builder, and Open Source Day project

### ISSUE THREAD

**Issue by PaulaPaul** [finos/a11y-theme-builder#779]
## Problem/Concern

The Call for Presentations/Projects is open for the Grace Hopper Celebration in October 2024!

Text from the announcement is below:
🌟 Save the Date! 🎉 GHC 24 is coming to Philadelphia, PA + Virtual on Oct 8-11, 2024, with Open Source Day kicking us off on Friday, Oct 4!

Get ready to experience insightful talks, cutting-edge workshops, and opportunities to connect with industry leaders and peers from around the globe!

📢 Our Call for Participation (CFP) is now open! Share your knowledge, experiences, and insights with a vibrant community of women and non-binary technologists. [CFP](https://lnkd.in/gv5FgKNd)

🏆 Plus, nominations for the prestigious Abie Awards are also underway. Recognize and celebrate the achievements of trailblazing women and non-binary people in technology. [Abie Awards](https://lnkd.in/g4vk7YqW)

Join us in the vibrant city of Philadelphia or virtually for an inspiring four-day event filled with incredible learning, networking, and career-building opportunities.

## Proposed Solution

We can propose a speaking session or panel session on Theme Builder, and also propose Theme Builder as an Open Source Day project along with a Collaboration Summit (in person/hybrid) at GHC.

In our community calls we will comment on this issue and track ideas and decisions, closing the issue once abstracts are submitted-

@lwnoble

**Comment by PaulaPaul** [comment]
Hoping to submit the talk from OpenUK to GHC, and also submit the A11y Theme Builder Product to Open Source Day as a featured project - @lwnoble the CFP is open but we have some time. Can talk about this at OpenUK-

**Comment by codyzu** [comment]
I want to help with this

**Comment by codyzu** [comment]
@lwnoble will submit ghc 24 and @codyzu will submit for open source days.

**Comment by PaulaPaul** [comment]
CFPs have been submitted! Thanks @codyzu and @lwnoble
