### ISSUE TITLE
[REQUEST] Provide information about Theme Builder to FINOS

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#784]
## Suggestion/Concern

@maoo from FINOS contacted us:

_I'm working on a landing page for FINOS Hosted platform (ie [www.finos.org/hosted-platforms](https://www.finos.org/hosted-platforms) ) , with the aim of raising visibility (and awareness) around the services that we host in our infrastructure._

 

_One of these platforms is going to be [try.a11y-theme-builder.finos.org](https://try.a11y-theme-builder.finos.org) and I'd like to ask you 1 or 2 paragraphs about the value of this service and why people should be interested to check it out._

 

_On top of that, I'm planning to add a "ribbon" on [a11y-theme-builder.finos.org](https://a11y-theme-builder.finos.org) , with a pointer to this landing page._

## Proposed Solution

I think that since this is the Hosted Platforms page, our paragraphs should be focused on how [https://try.a11y-theme-builder.finos.org](https://try.a11y-theme-builder.finos.org) specifically could help someone who is interested in FINOS hosted platforms.

**Comment by aaronreed708** [comment]
@PaulaPaul @lwnoble @codyzu: Here is what I came up with.  Feel free to use, modify or discard as you see fit.  Let me know when your final version is ready and I'll pass on to @maoo.  Thanks!

_Accessibility Theme Builder () is a project with the goal of empowering designers and developers with the ability to easily define design systems that are compliant with web accessibility standards.  Many of the WCAG 2.1 AA guidelines that address the visual appearance of your web pages require complex calculations to ensure your content is consumable by as diverse a population as possible.  Theme Builder enforces these guidelines in both light and dark modes and restricts user choices as necessary to prevent the creation of an inaccessible design system while still allowing the user the greatest flexibility possible._

_Please take Accessibility Theme Builder for a spin by visiting https://try.a11y-theme-builder.finos.org.  Using this service, you'll be able to define a color palette, create a default theme, and compose a design system that, when exported, can be consumed as design tokens by wireframe design tools as well as CSS by component libraries and applications.  Begin your journey toward accessibility compliance today!_

**Comment by maoo** [comment]
Perfect, thank you @aaronreed708 !
