### ISSUE TITLE
[REQUEST] Design LF Badges for Theme Builder

### ISSUE THREAD

**Issue by PaulaPaul** [finos/a11y-theme-builder#797]
## Suggestion/Concern
Design LF Badges based on #786 

## Proposed Solution

@lwnoble asked for a separate/related issue specifically to design the first three initial badges described in #786, and will contact Giselle so that she can comment on the issue and join the discussion-

**Comment by aaronreed708** [comment]
@chessel, @lwnoble wanted you to be looped in on this design.

**Comment by Chessel** [comment]
Yes! I would love to be looped in

**Comment by PaulaPaul** [comment]
Designs complete! Thank you @lwnoble and @Chessel!

We can track the ongoing work to enable the badging with LF in issue #786 

![Image](https://github.com/finos/a11y-theme-builder/assets/8395352/d61c978a-b293-4322-98f6-363151d9545c)
