### ISSUE TITLE
[DOCS] Create a location for links to videos from Community talks and other resources

### ISSUE THREAD

**Issue by PaulaPaul** [finos/a11y-theme-builder#798]
## Problem/Concern

In order to close #780 we need a process for publishing links from recorded presentations and talks, and video resources that can help us build and educate the Theme Builder community. 

* See discussion notes in #780 

## Proposed Solution

From discussion with the project team we decided to create a home in the Docs area of this repo and post the link from the State of Open Con 24 talk as a start, and include information in the README or other area(s) about where to find videos from talks and demo videos.

**Comment by codyzu** [comment]
@PaulaPaul this is already done, right? Let us know.

**Comment by evangk6** [comment]
Just needs to be merged: https://github.com/finos/a11y-theme-builder/pull/799

**Comment by evangk6** [comment]
Merged
