### ISSUE TITLE
[TB] Add ability to launch the deployed theme builder from our documentation

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#818]
## Problem/Concern

This work was started by @maoo in https://github.com/finos/a11y-theme-builder/pull/808.  Mao added a nav item called "Demo" to the top level navigation bar.  As you can see in the comments for the PR that we really wanted it to create a new tab/window and, using an image, let the user know that clicking here would launch a new tab/window.  So I set about researching how to do this.

Used these resources to come up with my proposed solution:

https://github.com/squidfunk/mkdocs-material/discussions/3008
https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
https://squidfunk.github.io/mkdocs-material/customization/?h=exte#extending-the-theme
https://github.com/squidfunk/mkdocs-material/blob/master/material/templates/partials/header.html

## Proposed Solution

I propose that we add an anchor element containing text like "Live Demo" and an icon next to the search bar in the documentation.  That way it is reachable by the user at any time.  Using an anchor with target="_blank" will cause the link to open in a new tab/window.

This is what it looks like on my machine:
<img width="989" alt="Screenshot 2024-04-04 at 1 51 14 AM" src="https://github.com/finos/a11y-theme-builder/assets/32913837/e56a02f6-12fc-4c73-9352-eafccde4caa4">

I'm just using the YouTube .svg file as a placeholder until a "correct" icon can be identified.

@maoo @chessel please review and see if this seems good for you.  If either of you have a good image to use that we can commit to open source, please send it to me.  Something like a "launch" icon (something like this, maybe? https://www.iconfinder.com/icons/326664/launch_icon)

**Comment by maoo** [comment]
Looks great @aaronreed708 ! Thanks for working on this!

**Comment by aaronreed708** [comment]
Using icon from Material Design Icons, part of Material Mkdocs.  Probably shouldn't be red.  Should it be a link or a button?  Asking Discover design team for suggestions.  The icons to the right of the red box are each clickable and take the user to GitHub, etc.  But they don't look clickable, to me, so not sure I should follow that style.

<img width="1166" alt="Screenshot 2024-04-08 at 5 38 31 PM" src="https://github.com/finos/a11y-theme-builder/assets/32913837/58b29768-0be5-4e0e-92e9-c25e6947aa64">

**Comment by aaronreed708** [comment]
deployed on dev.  Closing.
