### ISSUE TITLE
18 Apr 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#828]
## Date
20240418 - time

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Discuss 827
- [x] Discuss Mao Email
- [ ] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Updated #827 with answers
- #464 is near completion and Evan will set up time with Lise and Paula
- Decided on changes needed for #368
- #544, #686, #541: ghosted, possibly need to move back or use for Mentorship
- #629: believe we are done but confirming with Keith
- #738: almost complete and Lise will get out feedback thereafter
- #829, #744, #786: Paula gave updates on summit, including timeline.
- #830 created by Kristen
- Lise and Evan reviewed Maurizio's requests for prereqs for the mentorship program and sent email off/

## Action Items
- [x] Aaron to ask Keith to give a talk on the SDK that we can record.  A "Teach the Teachers" before we help the collaborators at the summit
- [ ] Lise to update video on mkdocs
- [x] Aaron to ask FINOS for context around click rates

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by kris-reed** [comment]
Kristen Reed

**Comment by PaulaPaul** [comment]
Paula Paul - Greyshore @PaulaPaul

**Comment by evangk6** [comment]
Evan K - DFS
Lise N - DFS

**Comment by aaronreed708** [comment]
I asked Keith for help finding the video that he had previously done for the SDK.
I opened an issue that we can use to update the video in mkdocs -> https://github.com/finos/a11y-theme-builder/issues/833

With these, minutes approved in today's meeting.
