### ISSUE TITLE
[TB] Fix Motion Sensitivity

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#830]
## Problem/Concern

Kristen reported that pressing the `Motion Sensitivity` button did not appear to have any effect.

**Comment by kris-reed** [comment]
In our meeting last week (4/10), Lise made note that the motion sensitivity button would not "turn off" when interacted with.

**Comment by Photon3009** [comment]
@Kayd396, could you please describe the issue regarding the motion sensitivity button? like what actions have already been taken regarding this issue? or what steps are still needed to be completed?

**Comment by kris-reed** [comment]
@Photon3009 I don't know the specifics. I was receiving a tour of the project and was asked to help remember that the motion sensitivity button would not "turn off."

**Comment by aaronreed708** [comment]
@Photon3009 

Hi @Kayd396, do you remember what you saw when the issue presented itself?  Did the checkbox not uncheck?  Or did the act of unchecking the checkbox not return Theme Builder to normal behavior?

So what the Motion Sensativity checkbox does is turn off, or drastically reduce, animations.  So, for example, if you load a design system in Theme Builder and select Molecules at the top and then select **Standard Button** from under **General Deskctop** molecule settings, you'll see 3 buttons in the **Example** section on the page.  If you hover over the **TERTIARY** button/text, you'll notice some animation that is used to outline the button.  And when you remove your mouse from the button it'll animate away the highlight.  If you slowly move your mouse over the button, it is even easier to see the animation that is happening.  So if you then select the checkbox for **Motion Sensativity** from the upper right in the **Theme Layers** dropdown, then you should notice that this animation stops occurring and the button simply becomes outlined or it removes the outline depending on its hover state.  Unchecking the checkbox will then return the default animation behavior.

When I just tried this, I did not see any. problems with the Motion Sensitivity behavior w.r.t. to this button.  Was there a different animation that shows the problem Kris?

**Comment by kris-reed** [comment]
@Photon3009 I would love to answer your questions, but I did not see the issue directly. The details might be better addressed by @lwnoble.

**Comment by Photon3009** [comment]
> @Photon3009
> 
> Hi @Kayd396, do you remember what you saw when the issue presented itself? Did the checkbox not uncheck? Or did the act of unchecking the checkbox not return Theme Builder to normal behavior?
> 
> So what the Motion Sensativity checkbox does is turn off, or drastically reduce, animations. So, for example, if you load a design system in Theme Builder and select Molecules at the top and then select **Standard Button** from under **General Deskctop** molecule settings, you'll see 3 buttons in the **Example** section on the page. If you hover over the **TERTIARY** button/text, you'll notice some animation that is used to outline the button. And when you remove your mouse from the button it'll animate away the highlight. If you slowly move your mouse over the button, it is even easier to see the animation that is happening. So if you then select the checkbox for **Motion Sensativity** from the upper right in the **Theme Layers** dropdown, then you should notice that this animation stops occurring and the button simply becomes outlined or it removes the outline depending on its hover state. Unchecking the checkbox will then return the default animation behavior.
> 
> When I just tried this, I did not see any. problems with the Motion Sensitivity behavior w.r.t. to this button. Was there a different animation that shows the problem Kris?

okay thanks @aaronreed708 now I got it!

**Comment by ravjot07** [comment]
![Screenshot from 2024-05-09 05-08-18](https://github.com/finos/a11y-theme-builder/assets/138920477/9442e3ea-0f8f-48a6-89d9-a23e032acb58)
Just an oveservation 
designSystem.layers.motionSensitivity.setPropertyListener("motionSensativityListener", layerChangeListener);
Typo error motionSensativityListener Should i correct this?

**Comment by aaronreed708** [comment]
It is just naming the listener, so not really an issue.  I tend to group those really minor things into other patches that I'm working on at the time.  But if you'd like to fix it, I'd be happy to review it.

**Comment by aaronreed708** [comment]
looked at with @lwnoble, couldn't not recreate.  Closing.
