### ISSUE TITLE
[TB] problem while installing theme builder

### ISSUE THREAD

**Issue by omesh-omg** [finos/a11y-theme-builder#834]
the error occurs due to :
```
interface Props extends SelectProps {
    children?: ReactNode
 }
```
in code/src/ui/src/mui-a11y-tb/components/Dropdown.tsx

the error is :

> 190.7 TS2312: An interface can only extend an object type or intersection of object types with statically known members.
> 190.7     2 | import { Select, SelectProps } from '@mui/material';
> 190.7     3 |
> 190.7   > 4 | interface Props extends SelectProps {
> 190.7       |                         ^^^^^^^^^^^
> 190.7     5 |     children?: ReactNode
> 190.7     6 | }
> 190.7     7 |

here is the issue for more detail in the material UI 
[link to the issue](https://github.com/mui/material-ui/issues/35728)

: the patch I have done is mentioned in the issue linked above 

```
type Props = SelectProps & {
    children: ReactNode;
  }

// interface Props extends SelectProps {
//     children?: ReactNode
// }

```
I have replaced it with this 
It will be difficult for newcomers to do it I have also faced it 

@aaronreed708 please look into it

**Comment by aaronreed708** [comment]
I fixed this in: [[TB] CVE scanning error reported](https://github.com/finos/a11y-theme-builder/issues/801) which is available on the `dev` branch, but not yet on `main`.  Marked this issue as a duplicate.  Already discussed with @omesh-omg on Slack.  Closing this issue.  Please re-open if you disagree with my assessment.  Thanks!
