### ISSUE TITLE
documentation enhancement in DEV_GUIDE.md

### ISSUE THREAD

**Issue by omesh-omg** [finos/a11y-theme-builder#850]
No mention of using `dev` branch as upstream not the `main`

**Comment by Sweetdevil144** [comment]
We can add a new section to the `DEV_GUIDE.md` after the 'Fetch Latest Code' section. This new section will provide instructions on how to set the `dev` branch as the upstream branch for development. Also, we can add abit of _dev-intro_ related to knowledge of `fetching` and `upstreams` to contributors.

Maybe adding the below section helps users.

```markdown
### Set Upstream Branch

After cloning the repository, it's recommended to set the `dev` branch as the upstream branch for development. 
This is a common practice in many development workflows where all the development happens in the `dev` branch and then it's merged into the `main` branch when it's ready for production. 

Here's how you can do it:


git checkout dev
git branch --set-upstream-to=origin/dev
```

**Comment by omesh-omg** [comment]
![image](https://github.com/finos/a11y-theme-builder/assets/64972958/abd85486-4029-40f0-9862-4dad066d678a)
I think this is what you are asking for ? Is this fine

**Comment by omesh-omg** [comment]
Please mention further suggestions if any

**Comment by Sweetdevil144** [comment]
LGTM !!

**Comment by omesh-omg** [comment]
https://github.com/finos/a11y-theme-builder/pull/848 the PR is merged we are closing this. @aaronreed708
