### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by Prasanth-S7** [finos/a11y-theme-builder#878]
Issue: npm run build fails when attempting to run locally

![Screenshot 2024-05-11 195849](https://github.com/finos/a11y-theme-builder/assets/127669274/9c280308-ba2f-42ad-93ce-375bda1cb050)

Problem:
The issue arises within the Dropdown.tsx file when attempting to import selectProps from Material-UI. Following this import, there is an attempt to extend a TypeScript type from an interface, which is not Possible.

Solution:
Converting Props into a TypeScript type should resolve this issue.

**Comment by ravjot07** [comment]
yes i have already figures it out 
try replacing this code with 
import React, { ReactNode } from 'react';
import { Select, SelectProps } from '@mui/material';

type Props = SelectProps & {
    children?: ReactNode;
};

export const Dropdown: React.FC<Props> = ({ children, MenuProps, ...rest }) => {
    const [anchorEl, setAnchorEl] = React.useState<HTMLElement | null>(null);
    const refContainer = React.useRef<HTMLDivElement>(null);

    React.useEffect(() => {
        if (refContainer.current) {
            setAnchorEl(refContainer.current);
        }
    }, []);

    return (
        <div>
            <Select
                {...rest}
                MenuProps={{
                    container: anchorEl,
                    ...MenuProps,
                }}
            >
                {children}
            </Select>
            <div ref={refContainer}></div>
        </div>
    );
};

**Comment by Sweetdevil144** [comment]
Issue already fixed within `dev` branch

**Comment by Prasanth-S7** [comment]
shall i close this issue @Sweetdevil144

**Comment by omesh-omg** [comment]
hello @Prasanth-S7  this is already fixed in the issue #801 which is merged in the dev branch. 
please use dev branch one way to do this by using CLI is 
![image](https://github.com/finos/a11y-theme-builder/assets/64972958/d26a7636-a727-489a-aef1-a3a138bc1eca)

I hope this  helps
