### ISSUE TITLE
[TB] No introdcution page for Components in the right  scrollable menu

### ISSUE THREAD

**Issue by omesh-omg** [finos/a11y-theme-builder#889]
![image](https://github.com/finos/a11y-theme-builder/assets/64972958/582e522c-f422-48f1-a8a7-e4c6b117bf62)

### Suggestion 
to add **Introduction page for components** in right scrollable menu as it is for  atoms, molecules, organisms

### Proposed Solution
Adding it on the top of right scrollable menu in the components page

![image](https://github.com/finos/a11y-theme-builder/assets/64972958/f3403252-9eaa-4038-91bb-fb83eea96b3f)

**Comment by aaronreed708** [comment]
makes sense to me

**Comment by omesh-omg** [comment]
Hey @aaronreed708 I have linked the PR to resolve the issue I think everything is okay from my end.
Wanted to know your suggestion on the introduction description mostly.

**Comment by omesh-omg** [comment]
This issue  is resolved ready to close it @aaronreed708.
