### ISSUE TITLE
[TB] Typography Font Settings - WCAG 4.1.2: Ensures every ARIA input field has an accessible name (#primaryFontSelect)

### ISSUE THREAD

**Issue by kburk1997** [finos/a11y-theme-builder#924]
## Problem/Concern
When I run Accessibility Insights for Web on the Typography Font Settings page, I get this issue for each select element:
### Issue
`Ensures every ARIA input field has an accessible name` ([aria-input-field-name](https://accessibilityinsights.io/info-examples/web/aria-input-field-name))
### Target application
[A11y ThemeBuilder](http://localhost:8080/designSystem/Sample)
### Element path
#primaryFontSelect
### Snippet
`<div tabindex="0" role="combobox" aria-controls=":r4:" aria-expanded="false" aria-haspopup="listbox" aria-labelledby="primaryFontSelect" id="primaryFontSelect" class="MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-1xd5...`
#### How to fix
    Fix any of the following:
      aria-label attribute does not exist or is empty
      aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
      Element has no title attribute
### Environment
Microsoft Edge version 125.0.0.0
This accessibility issue was found using Accessibility Insights for Web 2.42.0 (axe-core 4.8.4), a tool that helps find and fix accessibility issues. Get more information & download this tool at [http://aka.ms/AccessibilityInsights](http://aka.ms/AccessibilityInsights).
### Screenshot
![Screenshot of primary font select box without an accessible name](https://github.com/finos/a11y-theme-builder/assets/11298269/47036c4c-3b88-4d0b-8c39-2e5262ad7909)

## Proposed Solution
Ensure all select fields are properly labeled.
Reference: [Material UI React - Select - Accessibility](https://mui.com/material-ui/react-select/#accessibility)

**Comment by kburk1997** [comment]
I am now covered under my company's CCLA, so I can take this on if needed - this seems like a very small fix.

**Comment by aaronreed708** [comment]
> I am now covered under my company's CCLA, so I can take this on if needed - this seems like a very small fix.

If you can fix it, that would be great!  In this case, the label and the field are separated by text.  What is the best way to do this with Aria attributes?  I'm guessing if we label it incorrectly that a screen reader might read stuff out of order?

**Comment by kburk1997** [comment]
Probably using either Material UI's labelId property or aria-labelledby - as is, a screen reader will read the field as unlabeled, which causes confusion.

**Comment by kburk1997** [comment]
I was able to fix this issue locally by adding `id="primaryFontLabel"` to the `<div className="subtitle">` element, then adding `labelId="primaryFontLabel"` to the primary select.

This ensures that the text label is properly associated with the select field.

**Comment by kburk1997** [comment]
Just made a commit on my fork - can you please assign me this issue so I can mark it as in progress and raise a PR?

**Comment by kburk1997** [comment]
PR merged - closing
