### ISSUE TITLE
20 Jun 2024 - A11y Theme Builder Meeting Minutes

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#942]
## Date
2024-06-20 - time

## Zoom info
- Meeting link: https://zoom.us/j/91013899295?pwd=Qnh5UVN1aUZ4ak9tODgvMVNLNUg5Zz09
- Meeting id: 910 1389 9295
- Password: 123225
- Call-in: +1 929 205 6099 US (New York) (Check calendar for more options)

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] [Agenda item 1](https://github.com/finos/a11y-theme-builder/issues/838)
- [x] [Agenda item 2](https://github.com/finos/a11y-theme-builder/issues/927)
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Minutes
- No community working group this week
- #927 - Kathleen made two contributions, will look for more issues in a couple of weeks
- OSFF London - Cody mentioned there may be a table for us. He will reach out to Lise and Paula.
- Moved over unresolved action items from last week
- Cut meeting short in absence of Aaron, Lise and Paula.

## Action Items
- [ ] <i>(from last week)</i>Aaron and Evan need to break the Epic that will be worked on by the mentee into detailed and digestable issues
- [ ] <i>(from last week)</i> Lise to work with Aaron to update video in mkdocs documentation
- [ ] <i>(from last week)</i> Open issue to evaluate PenPot from Theme Builder perspective
- [x] Get all relevant assignees to #838
- [ ] ...

**Comment by codyzu** [comment]
Cody Zuschlag - Nearform

**Comment by evangk6** [comment]
Evan K - DFS

**Comment by kburk1997** [comment]
Kathleen Burkhardt - BlackRock

**Comment by omesh-omg** [comment]
Omesh- omesh-omg

**Comment by aaronreed708** [comment]
approved in this week's call
