### ISSUE TITLE
[TB] Minimum Target Area atom broken

### ISSUE THREAD

**Issue by aaronreed708** [finos/a11y-theme-builder#990]
## Problem/Concern

When I bring up the Minimum Target Area atom, I see stack exceptions in the display.

<img width="862" alt="Screenshot 2024-08-09 at 11 09 08 AM" src="https://github.com/user-attachments/assets/8877e945-d492-4c58-b9fc-aea33d87f33c">

This appears to be an issue where the index on an array is incorrect when trying to build the list of selectable values.  Probably introduced when I made all of those lint changes.

## Proposed Solution
Fix the index being used in the code to build the list of selectable values.

**Comment by toni-sharpe** [comment]
The merged PR suggests this issue can be closed.

In the PR decrioption, try `Fixes #<issue_no>` to have the PR close automatically close the issue

**Comment by aaronreed708** [comment]
verified on dev today.  Closing.  Thanks for the reminder, @toni-sharpe!
